# 11장 Word2vec의 개요와 응용

## 1. 단어를 숫자로 전환하기: Embedding

신경망 알고리즘으로 언어 데이터를 다루는 방법은 무척 다양합니다. 하지만 그 중 가장 먼저 사람들의 시선을 끌었고 지금까지도 다양한 방식으로 활용되는 기법은 Word2vec이라는 기법일 것입니다. Word2vec은 명칭 그대로 '단어'를 '벡터'로 바꾸는 기법입니다. 쉽게 말해 단어를 숫자로 바꾸는 기법이라는 말입니다. 벡터는 사실 여러 숫자를 묶어 놓은 것이니까요. 예를 들어 [345,12,3] 이런게 벡터죠. 

이렇게 여러 숫자를 묶으면 표현력을 높일 수 있습니다. 하나의 숫자로 표현하는 것보다, 여러 각도의 다양한 정보를 묶어서 표현할 수 있으니까요. 그래서 어떤 복잡한 정보를 숫자로 표현해야 할 때 벡터라는 형식을 쓰곤 합니다. 예를 들어 사회과학에서 한 사람의 다양한 측면을 조사하고 (예를 들어 키, 몸무게, 월소득, 연령, 현 직장 근속 연수를 조사했다고 가정하죠), 그걸 벡터로 표현하는 건 흔한 일입니다. [176, 75, 400, 42, 5] 뭐 이런 식으로 한 사람의 정보를 표현하는 거죠. 

Word2vec은 단어를 이런 벡터로 전환하겠다는 것입니다. 당연히 무작위의 벡터로 전환하겠다는 것은 아니고, 단어 간 의미 관계를 반영하여 숫자로 전환하겠다는 말이지요. 왜 굳이 가만히 있는 단어를 벡터로 전환하려고 하는 것일까요? 이것은 기존에 질적 대상이라 여겨졌던 것을 연산 가능한 대상으로 만드는 함의를 가집니다. 단어, 그리고 그것의 의미는 질적인 것이라 여겨졌습니다. 그래서 단어 의미 사이의 차이를 비교하거나 여러 단어의 의미를 합성하는 일은, 근본적으로 인간 고유의 종합 능력과 직관에 의존한 일이라 생각했습니다. 예를 들어 '비난'과 '비판'의 차이는, 인간의 종합 능력을 통해 판단해야 한다고 생각했다는 말입니다. 그런데 만약 '비난'과 '비판'이 둘 다 벡터로 전환되어 있다면 어떨까요? 그러면 둘 사이의 차이를 계산하는 일은 간단한 뺄셈으로 가능해집니다. 나아가 둘 사이의 거리를 계산할 수도 있고, 그걸 다른 단어쌍과 비교도 할 수 있을 것입니다. 예를 들어 '비난'과 '비판'의 거리와 '잔소리'와 '조언'의 거리를 비교할 수도 있는 것이죠. 

이렇게 단어를 벡터로 전환하게 되면, 단어를 컴퓨터가 하는 연산의 입력과 출력으로 삼을 수도 있게 됩니다. 컴퓨터는, 본질적으로 숫자를 가지고 계산을 하는 기계입니다. 그래서, 입력과 출력을 숫자로 전환할 수 있어야 컴퓨터에게 그와 관련된 일을 시킬 수 있습니다. 그렇기에 만약 단어를 숫자로 전환할 수 있고, 그 숫자들이 인간의 직관에 근거한 단어의 의미 파악과 단어간 의미 관계를 근사할 수 있을 정도로 말이 되면, 컴퓨터는 그 숫자를 가지고 '언어적으로 유의미한' 연산을 할 수 있게 되고, 결과적으로 컴퓨터에게 언어 활동을 시킬 수 있게 됩니다. 우리의 일상이 된 언어 AI 등도, 언뜻보면 마치 인간처럼 우리와 대화를 나누는 것 같지만, 사실 우리가 입력하는 언어를 숫자로 바꾸고 -> 그 숫자로 어떤 연산을 하고 -> 그 결과를 숫자로 출력하고 -> 출력된 숫자를 다시 언어로 바꿔서 우리에게 보여주는 것입니다. 

만약 그렇다면, 단어를 포함한 언어 표현을 실제 인간 언어 활동과 의미를 근사할 수 있는 숫자(벡터)로 전환하는 것은, 언어에 근거한 통계 모델과 서비스의 핵심적인 조건이라 할 수 있습니다. 그래서 이걸 일반적으로 지칭하는 용어도 있습니다. Embedding, 임베딩 이라는 용어가 그것입니다. embed라는 영어 단어는 사전을 찾아보면 '뭔가를 다른 뭔가에 단단히 끼워넣는 활동'을 의미한다고 나옵니다. NLP에서는 embedding을 단어와 같은 언어 표현을 숫자의 세계에 끼워넣는 것, 즉 언어 표현을 숫자 표현으로 전환시키는 모델이나 기법을 의미하는 용도로 쓰입니다. 이 embedding의 성능은 당연히 컴퓨터나 통계 모델을 활용한 언어 처리 성능 전반에 매우 큰 영향을 미칩니다.

당연하지만, 이것은 쉽지 않은 일입니다. 색깔을 RGB코드라는 숫자로 바꾸는 것처럼, 질적 대상을 숫자로 전환시키는 시도 자체는 사실 흔한 편입니다. 그런데 단어나 언어 표현은 그 중 난이도가 높은 편입니다. 

첫 번째, 모든 단어가 공유하는 뚜렷한 속성이나 특성이 불명확합니다. 앞에서 사람의 여러 속성값을 벡터로 변환했을 때처럼, 관심을 기울이는 속성이나 특성이 명확하면, 벡터 전환이 쉬울 수도 있습니다. 그 개별 속성이나 특성을 수치로 전환하여 묶으면 되니까요. 하지만 단어에서 '소득'이나 '연령'에 해당하는 핵심 속성이 있을거라 상상하긴 어렵죠. 굳이 찾자면 획수 같은 특성을 생각할 수는 있겠지만, 그런 속성이 단어의 의미를 잘 설명한다고 보기는 어렵습니다. 그러니 어떤 방식으로 벡터로 변환해야 할지 기준을 찾기가 어렵습니다. 

두 번째, 단어의 종류가 너무 많습니다. 핵심 속성이나 기준이 없다면, 남은 길은 실제 단어들 사이의 의미 관계를 임의의 길이의 벡터로 잘 표현하는 것입니다. 앞서 예시로 든 '비난'과 '비판'의 거리와 '잔소리'와 '조언'의 거리를 실제 인간의 직관을 잘 반영하도록 숫자를 설정하는 거죠. 그런데 이를 위해서 고려해야 할 단어간 관계가 너무 많습니다. 애초에 단어가 너무 많기 때문입니다. 예를 들어 기사 1000개만 모아놓아도, 그 안에서 고유 단어가 5000개 이상은 나올 공산이 큽니다. 딱 이 5000개 단어만 벡터로 전환한다고 해도 5000개 사이의 의미적 관계를 적절히 반영해야 합니다. 그런데 5000개에서 두 단어쌍을 골라내는 가짓수는 1200만 개를 훌쩍 넘어섭니다 ($\frac{5000!}{(4998!2!)}$). 고려해야 할 단어 간 관계의 숫자가 부담스럽게 많다는 말이죠. 

그런데 Word2vec이 신경망 알고리즘을 활용하여 제법 설득력 있는 embedding을 만드는 절차를 제안했던 것입니다. 그것은 과거의 embedding 시도보다 성능이 좋았고, 그래서 많은 이들의 주목을 받았던 것이죠. 물론 지금도 여전히 Word2vec이 언어 모델들에 주력 embedding 기법으로 많이 쓰이느냐 하면 그렇다고 보긴 어렵습니다. 하지만 그것이 도입했던 발상은 여전히 최신의 기법에도 남아 있다고 할 것입니다. 향후 절에서 좀 더 자세히 설명하겠지만, Word2vec의 핵심 발상 중 하나는 맥락을 통한 단어 예측 과제를 고도화함으로써 단어 벡터 표현을 얻는 것인데, 이 접근은 최신 기법에도 여전히 남아 있죠. 나아가 연구적인 활용 가능성은 생각보다 큰 편이고요. 그래서 이 장에서는 신경망을 활용한 언어 처리의 첫 사례로 Word2vec을 살펴볼 예정입니다. 

한 가지 미리 말씀드리자면, 제가 이 장의 내용 중 여러 부분을 설명하는데 사이토 고키의 [밑바닥부터 시작하는 딥러닝 2]라는 책에서 익힌 내용이 큰 도움이 되었습니다. 관심있으신 분은 이 책도 한 번 살펴보시면 도움이 되실거라 생각합니다!

## 2. Word2vec 이전의 embedding 시도

본격적으로 Word2vec으로 들어가기 전에, Word2vec 이전의 embedding 시도에 대해 간단히 알아보겠습니다. 왜냐하면 그것이 Word2vec의 설계의 특징과 성능적 장점을 잘 볼 수 있게 해주기 때문입니다. Word2vec 이전의 embedding은 기본적으로 '단어 사이의 동시 출현' 이라는 정보에 기댄 방법이 많았습니다. 예를 들어 100개 기사를 모아봤더니 500 종류의 단어가 관찰되었다고 합시다. 우리는 각 단어가 같은 문장에 어떤 단어와 출현했는지 몇 번이나 동시 출현했는지 세어보기로 합니다. 그러면 각 단어가 같은 문장에서 나머지 499개의 단어와 몇 번 출현했는지 정리할 수 있습니다. 이걸 500X500 행렬로 정리할 수 있죠. 그걸 앞쪽만 가져와서 표현하면 아래의 그림처럼 될 것입니다. 

<div style="text-align:center;">
    <img src="_static/figures/동시 발생 행렬 예시.jpg" width="400"><br>
</div>

이 그림은 '나무'라는 단어가 '바람'과는 4번, 풀과는 6번, AI와는 1번 같은 문장에서 출현했고, 컴퓨터와 비행기와는 같이 출현하지 않았음을 의미합니다. 나머지도 마찬가지입니다. 이것 말고도 다른 단어가 많겠지만, 간단히 살펴보기 위해 6개의 단어만 살펴보겠습니다. 그러면 여기서 우리는 간단하게 각 단어의 벡터 표현을 얻어낼 수 있습니다. 각 행 혹은 열이 벡터 표현이 되는거죠. 예를 들어 나무는 [0,4,6,0,0,1,...]이 되는 식입니다. 만약 이게 타당하다면, embedding은 그냥 단어들 사이의 동시 발생 횟수만 세어보면 될 것입니다. 그러면 이런 행렬을 얻을 수 있고, 각 행이나 열이 각 단어의 벡터 표현이 되는거죠. 

그리고 이렇게 접근하는건 단순함에 비해 타당한 면이 있습니다. 우리는 <2장 언어를 네트워크로 바라보기>에서 언어의 의미 작용이라는 것이 결국 작은 구성요소들 사이의 관계에 의해서 만들어진다는 점을 배웠습니다. 그 작은 구성요소를 단어로 설정한다면, 단어의 의미는 근처 단어와의 관계에 의해 만들어집니다. 소쉬르는 이를 '차이의 테제'라는 말을 통해 표현하였고, NLP에서는 이것이 단어 의미의 분포 가설 (distributional hypothesis) 라는 말로 존재하지요. 그러면, 어떤 단어의 기본적인 의미는 그것 근처에서 함께 쓰인 단어에 의해 규정된다고 말할 수 있을 것입니다. 

그리고 동시 출현 행렬은 바로 그 정보를 표현하고 있습니다. 물론 이 동시 출현 행렬의 다양한 버전이 있을 수 있습니다. 지금처럼 문장 동시 출현을 기준으로 만들 수도 있고, 단락이나 문서 동시 출현이라는 기준을 쓸 수도 있겠죠. 아니면 몇 단계 이내의 근접 출현이라는 기준을 쓸 수도 있을 것입니다. 하지만 핵심은 동일합니다. '근처 출현 단어의 종류와 빈도'가 그 단어가 다른 단어와 맺는 관계를 표현하고, 그래서 그 단어의 의미에 대한 핵심 정보가 된다는 것입니다. 그래서 어떤 단어 근처에 등장하는 단어의 종류와 빈도를 벡터로 표현하면, 그게 괜찮은 단어의 벡터 표현이 된다는 말이지요.

그런데 이런 '동시 출현 행렬'에 기반한 embedding은 편리하고 간단한 만큼 뚜렷한 단점을 갖고 있습니다. 크게 두 가지 문제가 있습니다. 첫 번째는 불용어와 관련된 문제이고, 두 번째는 벡터의 길이와 관련된 문제입니다. 각각 살펴보죠. 

일단 이런 접근은 불용어가 만들어내는 소음에 취약합니다. 불용어란, 영어의 관사처럼 별 의미 없이 자주 다른 단어와 함께 사용되는 단어들을 의미합니다. a, the, like 뭐 이런거죠. 이들의 벡터 표현은 어떨까요? 엄청나게 많은 단어들이 동시 출현했다고 표현될 것입니다. 이런 벡터 표현은 별 의미가 없죠. 다른 단어들에서는 더 큰 문제입니다. 예를 들어 영어에서 student라는 단어는 school이라는 단어와 의미상 관련이 깊을 것이고, 자주 함께 출현할 것입니다. 어떤 자료에서 한 100번 같이 출현했다고 하죠. 그런데 a, the, like 같은 단어가 student와 200번 같이 출현하는 일도 생길 수 있습니다. 그러면 school이라는 유의미한 동시 출현 단어의 정보가 상대적으로 부각되지 않을 수도 있습니다. 즉 소음에 정보가 가려지는 셈이죠. 

이걸 해결하기 위해서, 동시 출현 빈도 대신 PMI (Pointwise Mutual Information) 혹은 PPMI (Positive Pointwise Mutual Information) 같은 지표를 사용하기도 합니다. A라는 단어와 B라는 단어의 PMI는 아래와 같이 정의됩니다. 

$$
\begin{aligned}
PMI(A,B) = \log_2{\frac{P(A,B)}{P(A)P(B)}}
\end{aligned}
$$


아주 간단히 설명하면, PMI는 두 단어의 동시 출현 확률을 각 단어의 출현 확률의 곱으로 나눠줘서, 어떤 단어가 절대적으로 많이 출현해서 생기는 착시를 제어하려는 접근입니다. 이걸 쓰면, 불용어 같은 단어가 단순히 여기저기 많이 출현해서 생기는 효과를 없앨 수 있죠. 즉 어떤 단어와 어떤 불용어가 같이 많이 출현한다고 판정이 되어도, 불용어 자체의 출현 확률이 너무 높으므로, PMI는 동시 출현 빈도에 비해 낮은 점수를 가지게 되죠. 이런 식으로 소음을 억제하는 것입니다. 대신 각각 많이 출현했다고 보기는 어렵지만, 한 번 출현하면 함께 출현하는 경우가 많은, 즉 정말 의미적으로 연결성이 높은 단어쌍은 PMI가 높겠죠.

하지만 이런 접근으로도 해결할 수 없는 치명적 문제가 있습니다. 그건, '벡터가 너무 길고, 대부분 벡터의 구성 요소가 0이 된다'는 점입니다. 위의 처음 예로 돌아가보죠. 제가 앞의 6개 단어만 이미지로 표현했지만, 최초의 저희의 사례는 100개 기사를 모았더니 500 종류의 단어가 나오더라는 것이었습니다. 그러면 각 단어의 벡터는 길이가 얼마가 될까요? 500이 되어야 합니다. 그래야 나머지 단어들과의 동시 출현을 표현할 수 있죠. 그런데, 이 단어 숫자는 아주 쉽게 매우 커집니다. 예를 들어 기사를 100개가 아니라, 실제 분석에서처럼 한 10000개 모으면 어떻게 될거 같으세요? 일반적인 한국어 기사를 모으고, 그냥 명사나 고유명사로만 출현 단어를 한정해도, 전체 단어가 2만, 3만이 넘어가는 일은 아주 흔합니다. 그러면 각 단어를 표현하는 벡터의 차원이 역시 2만 3만이 되겠죠. 즉 2만이나 3만 차원 공간의 벡터로 표현된다는 말입니다. 

만약 벡터가 존재하는 공간의 차원수가 2만이 되고 3만이 되어도, 각 숫자가 유의미한 정보를 표현한다면 문제 없습니다. 하지만 보통 그렇지 않습니다. 문장 동시 출현을 기준으로 각 단어를 2만 차원의 벡터로 표현하면 무슨 일이 생길까요? 대부분의 칸이 0이 되는 일이 생깁니다. 당연합니다. 만약 단어가 정말 다른 단어와의 관계를 통해 의미를 표현한다면, 단어들이 주로 쓰이는 단어군이 있을 것입니다. 예를 들어 '풀잎'은 '나무'나 '바람' 등과 함께 사용되지, 엉뚱하게 'S&P500'이나 '반도체' 같은 단어와 사용되지 않습니다. 그리고 같이 등장할 법한 단어군은 전체 단어 종류에 비해서는 매우 작은 숫자죠. 그러면 풀잎을 표현하는 벡터의 대부분 자리에 0이 채워지는 일이 생깁니다. 

이건 데이터 관리, 처리 상 매우 큰 비효율을 낳습니다. 컴퓨터 입장에서 0도 숫자입니다. 실제 없는게 아니라, '그건 0이다'라고 표시해야 한다는 말입니다. 메모리를 그대로 먹죠. 그리고 이런 벡터을 가지고 연산을 할 때, 그 거대한 규모는 그대로 연산 부담으로 다가갑니다. 별 다른 소득도 없이 말입니다.

물론 이를 극복하려는 시도도 있었습니다. SVD(singular value decomposition) 같은 행렬 분해 기법을 활용하는 것입니다. 위와 같이 벡터, 나아가 행렬 대부분의 칸이 0인 행렬을 '희소 행렬' (sparse matrix) 라고 합니다. 이게 만들어내는 문제는 이미 많이 알려져 있습니다. 이를 극복하는 하나의 방법이, 이 희소 행렬을 그것의 핵심적인 정보만 요약하는 보다 작은 행렬들로 분해하는 것입니다. 다양한 기법이 있는데, 고유값 분해 (Eigenvalue decomposition)이나 특이값 분해 (Singular value decomposition) 같은 기법이 대표적입니다. 이런 기법을 동시 발생 행렬이나 PMI 행렬에 적용하면, 각 단어를 표현하는 보다 짧은 벡터, 즉 밀집 벡터 (dense vector)를 얻을 수 있습니다.

이 방법은, 순수하게 '정보 처리'라는 관점에서 보면 좋은 방법이라 할 수 있습니다. 선형대수에서 행렬분해는 잘 정리되어 있고, 그것의 성능도 입증되어 있지요. 그런데 이런 접근에도 여전히 한계가 있습니다. 첫 번째로, 행렬분해가 일반적으로 그리 쉬운 연산이 아닙니다. 계산량이 많고 그래서 연산 부담이 큽니다. 특히 단어수가 많아질 수록 계산 부담이 빠르게 증가합니다. 

더 곤란한 문제는, 결과를 만들기 위해 매번 처음부터 연산을 해야 한다는 점입니다. 사실 embedding의 경우, 기존의 작업을 활용하는 것이 효율적인 경우가 제법 많습니다. 예를 들어 제가 모종의 작업을 거쳐서 한국어 단어들에 대한 제법 괜찮은 embedding 결과를 산출해뒀다고 합시다. 즉, 여러 한국어 단어의 벡터 표현을 일반적인 수준에서 만들어 둔 것이죠. 그런데 제가 보건의료 분야에 특화된 embedding을 하고 싶다고 합시다. 뭐 보건의료 분야의 새로운 챗봇 같은걸 만들고 싶은 상황이라고 하죠. 그러면 일반적인 벡터 표현을 약간 수정하는게 합리적입니다. 일반적인 한국어 의미를 살리되, 보건의료분야에 맞춰서 세부 조정만 하면 되니까요. 예를 들어 일반적으로는 '전달'이 그냥 물건 건네주는 의미로 쓰이지만, 보건의료에서는 '전달'은 '의료'나 '체계'와 가깝게 쓰이는데, 그런걸 좀 조정하는거죠. 

그런데 행렬 분해 기법은, 이미 있는 산물을 세부 조정하는 방법의 활용이 어렵습니다. 그냥, 매번 정석대로 동시 출현 행렬 만들고, 필요하면 PMI 같은 점수 산출하고, 그걸 행렬 분해 기법으로 줄이는거죠. 이건, 실무상으로는 꽤 곤란한 면이 있습니다.

요컨대 이렇습니다. Word2vec 이전에도 embedding 시도들이 있었습니다. 그것은 가장 근본적으로는 '유의미한 맥락 단어를 세어본 결과'에 기반합니다. 동시 출현 기반 행렬, 혹은 근접 출현 기반 행렬이 그런 것들이죠. 이 자체는 언어에 대한 우리의 이론적 이해와 잘 일치하는 접근입니다. 하지만 문제도 있었죠. 불용어가 만들어내는 소음이나 벡터의 길이가 정보에 비해 너무 길다는 점이 그것입니다. 나름대로 이를 극복하려는 시도가 있었지만, 충분히 해결되었다고 보기는 어렵습니다. Word2vec은 이런 상황에서 나름의 돌파구를 만드는 기법이었습니다. 그리고 그것은, 아예 접근법을 달리하면서 시작되었습니다.

## 3. 신경망 알고리즘을 활용한 접근: Word2vec

Word2vec은 기존의 embedding에서 발생한 두 가지 핵심적 필요, 그러니까 밀집 벡터 표현을 얻고 싶은 것과 경우에 따라 기존의 embedding 결과를 활용하고 싶다는 필요를 신경망 알고리즘을 통해 해결합니다. 컨셉은 간단합니다. 신경망 모델이 '맥락 단어'로 '중심 단어'를 예측하거나, '중심 단어'로 '맥락 단어'를 예측하도록 세팅합니다. 그리고 해당 모델이 이 과제를 잘 해결하도록 훈련합니다. 그러면 그 모델 파라미터에 훈련 데이터가 된 단어들의 훌륭한 벡터 표현이 남게 된다는 것입니다. 즉 단어 예측 작업을 잘 해내는 신경망 모델을 만들면, 그 모델에 단어의 벡터 표현이 들어 있다는 말입니다.

하나하나 좀 더 살펴봅시다. 일단 맥락 단어는 뭐고, 중심 단어는 뭘까요? 언어 자료를 획득했다고 합시다. 그걸 토큰화 했다고 하죠. 그래서 토큰 연쇄로 변환했다고 하겠습니다. 그리고 이 토큰이 단어 레벨이라고 하죠. 기사 같은게 변환되었다고 가정하고, 이런 기사 문장이 있다고 하죠. 실제 기사 일부를 가져왔습니다. "1960년 자유당 정권의 부정선거에 항의하는 시민들을 향한 경찰의 발포로 16명이 희생된 3·15의거와 관련해 정부 차원의 공식 사과는 이번이 처음이다."(<이 대통령, ‘3·15의거’ 희생자·유가족에 “진심 어린 사과·위로”>, 경향신문, 3월 15일)

이걸 토큰화해서 토큰 연쇄 자료로 만들었다고 하겠습니다. [1960년, 자유당, 정권, 부정선거, 항의, 시민, 향한, 경찰, 발포, 16명, 희생, 3·15의거, 관련, 정부, 차원, 공식, 사과, 이번, 처음]. 엄밀한 결과는 아니지만 예시를 위해 그냥 진행하겠습니다. 그리고 '맥락'을 판단하는 길이를 3으로 잡겠다고 하겠습니다.

그러면, 다섯 번째 단어인 '항의'라는 단어의 맥락 단어는, '자유당', '정권', '부정선거', '시민', '향한', '경찰'이 됩니다. 즉 앞 뒤로 3칸 이내에 있는 단어들이 맥락 단어라는 말입니다. 반대로 '자유당', '정권', '부정선거', '시민', '향한', '경찰'라는 맥락 단어의 중심 단어는 '항의'가 됩니다.

Word2vec은 주어진 언어 자료에서 맥락 단어들로부터 중심 단어를 맞추는 작업이나, 중심 단어로부터 맥락 단어를 맞추는 작업을 수행하는 신경망 모델을 만듭니다. 위에서 보다시피, 특별히 가공되지 않은 일반적인 언어 자료가 주어져도, 맥락 단어 -> 중심 단어나, 중심 단어 -> 맥락 단어 문제를 아주 많이 만들 수 있습니다. 즉 일반적인 문헌 자료에서 학습 자료를 풍부하게 얻을 수 있다는 말입니다. 여담이지만, 이런 접근을 자기지도학습(self-supervised learning) 이라고도 부릅니다. 보통 지도학습이 가능하기 위해서는 인간이 레이블링 한 데이터가 필요합니다. 그래야 문제와 정답쌍을 갖고 시작할 수 있거든요. 그런데 특별히 레이블링 하지 않은 언어자료에서 일정한 논리를 가지고 문제와 정답쌍을 가져오는거죠. 

이렇게 확보된 자료, 즉 수많은 문제-정답쌍으로 신경망 모델을 훈련시킵니다. 맥락에서 중심을 잘 맞추는, 혹은 중심에서 맥락을 잘 맞추는 신경말 모델을 훈련시킨다는 말입니다. 그러고 나면, 이 신경망 모델에 단어의 벡터 표현이 담기게 됩니다. 

회귀분석에 익숙하신 분들이라면 이런 접근을 쉽게 이해하실 수 있을 겁니다. 보통 추론을 목적으로 한 회귀분석은, 관심 응답 변수를 설명변수를 활용해 잘 설명하는 모델을 학습한 후, 그 모델의 파라미터로부터 정보를 얻어내는 방식으로 활용됩니다. 그런데 Word2vec은 그걸 신경망 모델로 하는 것입니다. 뒤에 좀 더 자세히 설명하겠지만, 정확히는 2층 신경망 모델이라는 상대적으로 간단한 모델을 활용하지요.

구체적으로 모델의 어떤 파라미터를 활용하는지는 향후 좀 더 자세히 설명드릴 것입니다. 그 전에, 이런 전환이 기존의 embedding 접근과 아주 다른 것임을 지적하고 넘어가려 합니다. 기존의 방식은 '근처 단어' 혹은 '맥락 단어'를 '세어서 정보를 추출하는 접근'이라 할 수 있습니다. 근처 단어나 맥락 단어를 정의하는 방식은 다양할 수 있지만, 여튼 어떤 단어의 근처 단어나 맥락 단어를 세어서 기초 정보로 활용합니다. 모든 시작은 이 세어본 결과입니다. 

반면 Word2vec은 근처 단어나 맥락 단어를 세는 것이 아니라, 그것을 가지고 '예측 작업'을 수행합니다. 맥락 단어로부터 중심 단어를 예측하거나, 중심 단어로부터 맥락 단어를 예측하는 작업을 한다는 것입니다. 이걸 잘 해내는 모델을 상대적으로 간단한 모델을 만들면, 단어를 밀집 벡터로 전환하는 정보를 포함할 것이라는 거죠. **이건 '세어보는 작업에 기댄 접근'을 '예측하는 작업에 기댄 접근'으로 전환한 것입니다.** 그리고 이 전환은, 사실 지금 세계를 휩쓸고 있는 트랜스포머 아키텍쳐 기반 embedding에도 여전히 유지되고 있습니다. 예측 작업은 오히려 다양하게 확장되고 있죠 (다음 문장 여부 판정이나 가려진 단어 예측 등으로 확장되는 중입니다.).

제 생각에 이는 언어의 관계적 측면을 기존과 다른 방식으로 활용한 결과입니다. 앞서 언급한 '맥락 단어 세어보기'에 기초한 접근도 언어의 분포 가설 등에 기대고 있습니다. 그런데 분포 가설을 활용하는 방식이 꼭 그것만 있는게 아니라는 걸 Word2vec이 보여준 것이지요. 만약 분포 가설 혹은 소쉬르의 차이의 테제가 말이 된다면, 맥락 단어로부터 중심 단어를 예측하거나 거꾸로 중심 단어로부터 맥락 단어를 예측할 수 있다고 볼 수 있습니다. 그걸 해내는 구체적인 방법이나 메커니즘을 우리가 다 통제할 수 없지만, 표현력이 높은 모델과 알고리즘으로 그 작업을 고도화하면, 결과로 나오는 모델에 분명 embedding에 대한 정보가 있을 거라고 기대한 거죠. 제 생각에 Word2vec의 핵심적 중요성은, 그 자체의 성능보다, 이런 식의 '표현력 높은 모델을 활용한 접근법'을 개척한 것에 있습니다.

## 4. Word2vec 모델의 설계와 배경

### 4.1. 두 개의 아키텍쳐

자 그럼 좀 더 구체적으로 Word2vec이라고 하는 방법에 대해 알아봅시다. 앞서 말한 것처럼, Word2vec은 '단어 예측 작업'을 하는 신경망 모델을 만들고, 그 모델이 예측을 잘하도록 훈련하고, 훈련된 신경망 모델에 포함된 단어의 벡터 표현을 얻는 기법입니다. 이때 사용되는 신경망 모델은 2층 신경망 모델입니다. 10장에서 말씀드렸듯, 2층이라고 하면, 이는 은닉층이 하나라는 뜻입니다. 그래야 입력층, 은닉층, 출력층, 이렇게 구성되는데, 보통 입력층은 층수 계산에서 제외되므로, 2층 신경망이 되거든요. 즉, Word2vec은 은닉층이 하나인 신경망 모델을 예측 작업에 활용합니다. 

그런데 여기서 두 개의 아키텍쳐가 나뉘어집니다. 하나는 CBOW, continuous bag of words라고 이름이 붙은 아키텍쳐이고, 다른 하나는 Skip-gram 이라고 이름이 붙은 아키텍쳐입니다. 이렇게 나뉘어지는 것은 예측 작업이 두 종류로 나뉘어질 수 있기 때문입니다. 앞서 봤듯, '맥락 단어'를 가지고 '중심 단어'를 예측하는 작업이 가능합니다. 거꾸로 '중심 단어'로 '맥락 단어'를 예측하는 것도 가능하겠지요. 

앞서 든 예를 가지고 다시 보겠습니다. 
- "1960년 자유당 정권의 부정선거에 항의하는 시민들을 향한 경찰의 발포로 16명이 희생된 3·15의거와 관련해 정부 차원의 공식 사과는 이번이 처음이다."(<이 대통령, ‘3·15의거’ 희생자·유가족에 “진심 어린 사과·위로”>, 경향신문, 2026년 3월 15일)
- 토큰화 자료입니다 [1960년, 자유당, 정권, 부정선거, 항의, 시민, 향한, 경찰, 발포, 16명, 희생, 3·15의거, 관련, 정부, 차원, 공식, 사과, 이번, 처음].

맥락의 길이인 window를 2로 잡는다고 할 때, '자유당', '정권', '항의', '시민'이라는 입력을 주면 그 가운데에 나오는 '부정선거'를 예측하는 2층 신경망 모델을 만들 수 있습니다. 이게 CBOW 아키텍쳐로 Word2Vec을 만드는 방식입니다. 반대로 '부정선거'를 입력으로 주고, 그 주위에 나오는 '자유당', '정권', '항의', '시민'을 예측하도록 하는 2층 신경망 모델을 만들 수 있습니다. 이게 Skip-gram 아키텍쳐로 Word2Vec을 만드는 것입니다. 

사실 이렇게만 설명드리면 약간 추상적으로 느껴집니다. 그러니, 구체적으로 모델을 설계해보겠습니다. 먼저 CBOW로 하는 것부터 살펴보죠.

### 4.2. CBOW 아키텍쳐 기반 Word2vec

2층 신경망 모델을 활용한다는 점과 CBOW 아키텍쳐 (디자인)을 사용한다는 점은 정해졌지만, 좀 더 구체적으로 학습시킬 모델의 형태를 확정하기 위해 미리 정해야 할 것이 있습니다. 첫 번째는 window의 크기입니다. 즉 중심 단어의 주위 어느 정도를 맥락으로 볼 것이냐를 정해야 합니다. 이를 2로 설정하면, 중심 단어 앞 두 단어와 뒤 두 단어를 맥락으로 보겠다는 것입니다. 다른 숫자로 설정하면 그에 맞춰서 변화할 것입니다. 두 번째는 우리가 단어를 전환하기를 원하는 벡터의 구성 요소 개수입니다. 즉 단어를 100개의 숫자를 뭉쳐서 표현할지, 200개의 숫자를 뭉쳐서 표현할지 정해야 합니다. 벡터의 차원을 정한다고도 설명합니다. 이 두 가지가 연구자가 설정하는 핵심적 요소입니다. 일종의 하이퍼 파라미터죠.

설명을 위해 window 크기는 1로, 원하는 벡터 구성 요소의 개수는 3으로 했다고 (즉 3차원 공간의 벡터로 전환하겠다고 결정) 하겠습니다. 그리고 단순화를 위해 단어가 딱 다섯 종류만 있다고 하겠습니다. (자유당, 정권, 부정선거, 항의, 시민) 그러면 모델의 형태를 10장에서 종종 본 시각화 스타일로 표현하면 아래와 같아집니다. 
<div style="text-align:center;">
    <img src="_static/figures/cbow_vertical_input.png" width="800"><br>
</div>

- 입력층 표현: one-hot vector

자 하나하나 설명해보죠. 일단 두 개의 단어로 하나의 단어를 맞춰야 하는 상황입니다. 정권'과 '항의'를 넣어서 '부정선거'가 가운데에 있음을 예측해야 하는 상황이라는 말입니다. 다시 말하지만, window는 1입니다. 그런데, '단어'를 신경망 모델에 넣으려면 이걸 어떻게 숫자로 표현해야 할까요? 애초에 우리가 단어를 숫자로 바꾸려고 Word2vec을 활용하는 건데, 그걸 하려면 단어를 숫자로 일단 바꿀 수 있어야 하는 난감한 상황입니다. 

그런데, 아무런 정보가 없을 때 단어를 숫자로 전환하는 기초적인 방법이 있습니다. one-hot vector가 그 중 하나입니다. 굳이 한글로 번역하자면 '한 칸만 활성화된 벡터' 쯤 될텐데, 그냥 원핫 벡터라고 부르겠습니다. 이 원핫 벡터는 말 그대로 벡터를 구성하는 여러 숫자 중 딱 하나만 1이고 나머지는 다 0인 벡터를 의미합니다. [0,0,0,1,0] 이런게 원핫 벡터죠. 그러면, 어휘가 n개 있다고 하면, 그 모든 어휘를 n차원 공간의 원핫벡터로 표현할 수 있습니다. 모든 어휘에 순서를 부여하고 (예를 들어 사과는 첫번째 단어, 배는 두번째 단어...이런 식이죠), 각 단어를 자기 위치에만 1을 적고 나머지는 다 0을 만드는 식으로 표현하는 것입니다. 아무런 정보가 없을 때 흔히 쓰는 단어의 수치적 표현 형식입니다. 

그래서 위에서 입력 층에 들어갈 두 개의 단어를 두 개의 5차원 원핫 벡터로 표현한 것입니다. 지금 단어가 딱 다섯 개만 있다고 가정했습니다. 그래서 5차원 공간의 원핫 벡터로 표현된 것이지요. '정권'과 '항의'를 넣어야 하는데, 정권은 두 번째 단어이고, 항의는 네 번째 단어이니, 각각 그곳만 1로 표현되어 있습니다.

- 은닉층에서의 변환

자 그럼 이 입력 벡터들이 은닉층으로 들어가 다른 벡터로 변환됩니다. 앞서 one-hot vector은 (1X5) 이라는 형태(shape)로 표현되어 있습니다. 그런데 우리는 각 단어를 구성요소가 셋인 3차원 공간의 벡터로 만들고 싶습니다. 모든 단어를 [?,?,?] 형식으로 표현하고 싶다는 말입니다. 이 경우 우리는 은닉층에서 일어나는 변환이 이 목표를 반영하게 합니다. 즉, 은닉층에서 각 원핫 벡터가 3차원 공간의 벡터로 변환되도록 한다는 말입니다. 

이 경우에는 그러기 위해 (5X3) 라는 형태의 가중치 행렬을 각각의 입력에 동일하게 곱해줍니다. 그게 은닉층에서 일어나는 핵심 변환의 내용이죠. 이런 전환을 거치면 입력값들은 각각 (1X3) 형태의 3차원 벡터가 되겠죠. 우리가 고등학교 행렬 시간 (혹은 그 이후에 기초 수학 시간에서^^) 배웠듯, (1X5)와 (5X3)을 곱하면 (1X3) 형태가 나옵니다. 이렇게 만들어진 두 개의 벡터를 평균내거나 합치면, 하나의 은닉 표현이 만들어집니다. 그게 은닉층의 출력 벡터가 됩니다.

- 출력층에서의 변환

자 그런 다음 바로 출력층 변환이 시작됩니다. 은닉층에서 변환되어 나온 벡터를 단어 예측용 점수로 바꾸고 싶습니다. 10장에서 이미지 분류기 학습에 대해 알아보셨을 때 한 것과 동일합니다. 사실 '단어 예측 작업'이란 것이 여러 후보 단어 중 무엇이 여기에 해당할지를 선택하는 문제거든요. 이미지를 주고 어떤 범주에 해당할지 선택하는 구도와 동일하죠. 그때, 가능한 이미지 범주들 각각에 대해 점수를 만들었습니다. 여기서도 동일합니다. 전체 단어가 다섯 종류이니, 다섯 개의 점수를 만들면 되죠. 그 점수들을 각각 단어에 해당할 확률로 변환하는 것입니다. 

이를 위해 (3X5) 형태의 가중치 행렬을 여기에 곱해줍니다. 지금 은닉층 변환을 마친 벡터가 (1X3) 형태의 벡터임을 기억하세요. 여기에 (3X5) 가중치 행렬을 곱하면 (1X5) 형태의 벡터가 되겠죠. 그게 지금 그림에서 출력층의 최종 변환이 됩니다. 이 다섯 개의 숫자는 각각 단어에 대한 점수가 됩니다. 보통 이걸 확률로 변환을 합니다. 10장에서 배운 softmax 함수를 활용하는 거죠. 그러면 (1X5) 형태의 벡터가 확률 분포 형태가 됩니다.

- 손실 (Loss) 계산과 신경망 모델 훈련

자 그럼 입력이 들어가면, 뭔가 선택을 하게 되는 모델은 만들어진 셈입니다. 다만 이게 당연히 처음에는 정확하지 않겠죠. 그럼 10장에서 배운 것처럼, 현재 모델이 정답에서 얼마나 먼 판단을 하는지, 현재 출력값의 '손실'을 계산하고, 그것을 줄이는 방향으로 파라미터를 조정해야 합니다. 

지금처럼 신경망 모델의 출력이 여러 범주의 확률로 주어진 상황에서 보통 손실은 cross-entropy를 사용해서 계산합니다. 10장에서 배웠죠. 이 수치는 해당 케이스의 정답에 모델이 부여한 확률이 높으면 떨어지고 낮으면 올라갑니다. 그러면 여기서 우리가 앞서 배운 역전파 알고리즘이 들어옵니다. 이를 통해 이 신경망 모델의 파라미터를 손실을 줄이는 방향으로 조절하죠. 그럼 구체적으로 어떤 수치가 조절될까요? 핵심적으로는 위 그림에 나온 W와 W', 즉 입력 벡터에 곱해지는 가중치 행렬과, 은닉층 출력에 곱해지는 가중치 행렬의 숫자들이 조절될 것입니다. 여러 훈련 데이터에서 손실을 줄이는 방향으로 말입니다.

- 단어의 벡터 표현 추출

자 이렇게 우리가 설정한 신경망 모델의 훈련이 충분히 진행되었다고 합시다. 결과적으로 좋은 성능을 가지게 되었다, 그러니까 맥락 단어 두 개를 넣어주면 중심 단어를 잘 맞추는 모델을 만들었다고 가정하자는 말입니다. 

그런데 사실 Word2vec을 하려고 할 때, 기본적인 목표는 단어의 벡터 표현을 얻는 것입니다. 단어 맞추는 기능을 얻으려고 한 것이 아닙니다. 그럼 단어의 벡터 표현은 어디에 있을까요? 그건, W, 즉 입력 벡터에 곱해지는 가중치 행렬에 있습니다. 이 가중치 행렬이 단어의 벡터 표현을 담고 있습니다. 

위 그림에서 보다시피, 이 간단한 사례에서는 W가 (5X3) 형태의 행렬입니다. 그리고 여기서 각 행이 다섯 개 단어의 벡터 표현이 됩니다. 아래 그림처럼 말이지요. 

<div style="text-align:center;">
    <img src="_static/figures/W2V 가중치 행렬 예시.jpg" width="400"><br>
</div>

이것이 CBOW로 구현한 Word2Vec의 핵심 사항입니다. **맥락 단어로 중심 단어를 잘 예측하는 간단한 신경망 모델을 만들면, 입력층에 곱해지는 은닉층의 가중치 행렬이 각 단어의 좋은 벡터 표현이 된다는 것이 전체 골자이지요.**

### 4.3. Skip-gram 아키텍쳐 기반 Word2vec

그럼 다음으로는 skip-gram 디자인 기반 Word2Vec을 알아봅시다. 세팅은 위에서 활용한 것과 동일하게 만들겠습니다. 즉 맥락을 판단하는 window는 1이고, 단어를 3차원 공간의 벡터로 (즉 구성요소 개수가 3인 벡터) 만들고자 합니다. skip-gram 디자인은 CBOW와 반대로 중심 단어를 입력하면 맥락 단어를 예측하게 만듭니다. 즉 CBOW가 '정권'과 '항의'를 넣으면 '부정선거'가 나오도록 했다면, Skip-gram은 거꾸로 '부정선거'를 넣으면 '정권'과 '항의'가 나오는 것이지요. 그림으로 보면 아래와 같습니다.

<div style="text-align:center;">
    <img src="_static/figures/skipgram_vertical_output.png" width="800"><br>
</div>

맥락 -> 중심이 아니라 중심 -> 맥락이라는 점을 제외하면, CBOW 때와 거의 동일합니다. 다만 이 근본적 차이가 만들어내는 부대적 차이가 존재할 뿐입니다.  

일단 입력 형식은 원핫 벡터라는 점은 동일합니다. 아직 단어의 벡터 표현이 없으니 당연하죠. 지금은 '부정선거'라는 중심 단어를 넣고 '정권'과 '항의'를 맞추는 상황이니, 세 번째 단어인 '부정선거'가 입력값이고, 그래서 세번째 칸만 1인 벡터가 들어갑니다. 

은닉층 변환도 거의 동일합니다. (1x5) 형태의 벡터에 (5x3) 형태의 행렬을 곱합니다. 이것이 첫번째 가중치 행렬 W입니다. 그러면 (1x3) 형태의 벡터가 되죠. 그게 은닉층에서 일어나는 변환입니다. 다만 CBOW에서는 맥락 단어가 여럿이라 이 (1x3) 벡터가 여럿이 나오고 이들이 더해지거나 평균되는 과정이 있었는데, Skip-gram은 애초에 입력이 하나이니 그럴 필요가 없다는 점이 차이입니다. 

출력층 변환도 거의 유사합니다. (1x3) 형태의 은닉층 출력 벡터에 (3x5) 형태의 행렬을 곱합니다. 두번째 가중치 행렬 W'입니다. 최종적으로 (1x5) 벡터를 만들고, 이들 각각을 소프트맥스 함수를 거쳐 5개의 후보 단어에 대한 확률로 만들기 위함입니다. 다만 CBOW와 달리, 예측해야 할 단어가 여럿입니다. 맥락으로 주어진 단어는 복수이니까요. 지금은 '정권'과 '항의' 두 가지이죠. 그래서 이를 표현하기 위해 위 그림에서는 출력 벡터를 둘로 나눠서 표현하였습니다. 하지만 이 둘이 다른 벡터는 아닙니다. W'을 공유하기 때문입니다. 

손실 계산과 훈련 파트도 유사합니다. 다만 Skip-gram의 경우, 손실이 계산될 단어가 여럿입니다. Cross-entropy를 사용하여 손실을 계산하되, 이 번에는 두 개의 단어를 예측해야 하니, 두 개의 손실값이 나오겠죠. 보통 이를 평균합니다. 즉 '정권'이라는 단어에서 나오는 손실과 '항의'라는 단어에서 오는 손실을 평균한다는 말입니다. 그리고 이 평균 손실에 근거하여 역전파 알고리즘을 통해 모델 파라미터를 업데이트하지요. 핵심 파라미터는 W와 W'을 이루는 각 entry 값들입니다. 

그리고 마지막으로 단어의 벡터 표현을 얻는 장소는 동일합니다. W가 그것입니다. W의 각 행이, 각 단어의 벡터 표현이 됩니다.

## 5. Word2Vec이 작동하는 이유

4절에서 살펴보신 W2V은 모델이라는 관점에서 보면 무척 간단한 모델입니다. 만들기도 어렵지 않습니다. Word2Vec을 잘 훈련시키고 나면 우리는 W, 즉 은닉층 가중치 행렬에서 단어의 벡터 표현을 얻을 수 있다고 생각합니다. 그럼 이제 중요한 질문을 던져봅시다. 이 과정이 왜 단어의 벡터 표현을 만들게 되는 걸까요? 왜 W는 단어의 벡터 표현을 갖게 될까요? **즉, 이게 왜 작동하는 걸까요?**

이해의 편의를 위해 CBOW를 W2V의 구체적인 형태라 가정하고 설명을 진행해보겠습니다. 이 경우 Word2Vec을 훈련시키는 신경망 모델은 맥락을 주면 중심 단어를 예측하는 모델입니다. 이런 모델이 성공적으로 작동하려면 어떤 기능이 필요한지 생각해봅시다. 일단은 입력되는 단어에서 오는 정보를 정확히 파악해야 합니다. 즉 지금 다루는 맥락이 뭔지 알아내야 합니다. 다음으로는 이렇게 만들어진 맥락 정보로부터 출력될 단어의 가능성을 계산해야 합니다. 즉 1. 입력 단어들이 만들어내는 맥락 정보를 종합하고, 2. 그 정보로부터 각 단어의 출현 확률을 계산하는 기능이 필요하다는 말입니다. 

그런데 모델의 구도상, 1. 입력 단어들이 만들어내는 맥락 정보를 종합하는 기능을 하는 역할은 은닉층이 해야 합니다. 그리고 은닉층에서 일어나는 연산의 핵심은 원핫벡터에 W가 곱해지는 것입니다. 그게 맥락으로 주어진 단어마다 이루어지죠. 그런데 원핫벡터, 즉 하나만 1이고 나머지는 다 0인 벡터와 W가 곱해지면 어떤 일이 일어날까요? **W의 행 중 하나를 고르는 효과가 발생합니다.** 예를 들어 아래처럼 곱해진다고 하죠. 


<div style="text-align:center;">
    <img src="_static/figures/W2V 은닉층 변환 예시.jpg" width="700"><br>
</div>

자 그림처럼 입력으로 주어진 원핫벡터에서 두 번째만 1이라고 하겠습니다. '정권'이 두 번째 단어니까 그렇죠. 거기에 W라는 (5x3) 행렬이 곱해지면, 최종적으로 (1x3)으로 정리된 벡터가 나옵니다. 일단 (1x5)와 (5x3)를 행렬 곱을 하면, (1x3)형태가 나오는건 상식이죠. 그런데 실제 연산 과정을 생각해보면, 사실상 이게 W, 즉 (5x3) 행렬에서 행을 '고르는' 일에 다름 아닙니다. 

이는 입력이 원핫 벡터이기 때문입니다. 행렬곱을 정석대로 하면, 주어진 원핫벡터를 W, 즉 (5x3) 행렬의 각 열(column)과 dot product를 계산하여 그 세 개의 결과를 (1x3) 벡터에 기록하게 됩니다. 우리가 고등학교때 배운, '짝맞춰 곱해서 더하기'를 각 열마다 한다는 말입니다. 그런데 그 과정에서 W의 대부분 숫자는 별 의미가 없습니다. 원핫벡터에서 0이 기록된 부분들이 W의 숫자가 무엇이든 다 0으로 만들기 때문입니다. 유일하게 의미가 있는 부분은 원핫벡터에서 1이 적혀 있는 위치, 즉 W의 각 열에서 두 번째 숫자, 그러니까 사실 W의 두 번째 행에 있는 숫자들 뿐입니다. 그래서 사실 연산의 결과는 그림에서 빨간색으로 표현된 W의 두번째 행을 그대로 가져온 것과 동일합니다. 

요컨대 **은닉층에서 일어나는 변환의 핵심은 사실상 '행 고르기'입니다.** 그리고 단어마다 W의 행이 하나씩 할당되어 있는 셈이죠. 어떤 단어가 입력되면, 그 단어에 해당하는 행이 출력됩니다. CBOW의 경우 여러 개의 단어가 입력되기에 (맥락 단어들이 입력되죠) 여러 행이 출력되어 평균되거나 합쳐지는 방식으로 종합됩니다.

신경망 모델이 단어 예측을 잘 하기 위해서는, 은닉층에서 만들어지는 이 벡터가 맥락 정보를 잘 표현해야 합니다. 그것이 출력층에서 각 단어의 확률을 계산해내는 가장 기본적인 정보가 되기 때문입니다. 이 은닉층에서 만들어지는 벡터에 출력층 변환 연산이 가해져서, 각 단어의 확률이 만들어집니다. 그래서 이 신경망 모델이 훈련을 통해 단어 예측 작업을 잘 해내게 되면 될수록, 은닉층은 입력된 맥락 정보를 잘 표현하게 될 것입니다. 

그런데 **은닉층 연산의 핵심이 'W에서 행 고르기'라는 점 때문에, 성능이 개선될 수록 W의 각 행이 각 단어들의 '용법에 기초한 의미를 반영'하는 효과가 발생합니다.** 은닉층에서 일어나는 변환 연산이 성공적이라는 말은 무슨 말일까요? 여러 가지가 있겠지만, 무엇보다 비슷한 맥락은 비슷한 벡터로 표현하고, 다른 맥락은 다른 벡터로 표현해야 합니다. 용법상 비슷한 의미를 표현해야 할 단어는 비슷한 벡터로 표현해야 하고, 반대는 다른 벡터로 표현해야 한다는 말입니다. 예를 들어 아래의 두 가지를 보죠. 

- '자유당 **정권**의 부정선거에 항의하는 시민들' [자유당, 정권, 부정선거, 항의, 시민]
- '자유당 **정부**의 부정선거에 항의하는 시민들' [자유당, 정부, 부정선거, 항의, 시민]

두 문장 모두 말이 됩니다. 사람들이 사용할 법한 문장이죠. 그런데 여기서 '부정선거'를 중심 단어로 볼 때, 두 개의 맥락이 생깁니다. 하나는 '정권'과 '항의'가 입력되는 맥락이고, 다른 하나는 '정부'와 '항의'가 입력되는 맥락입니다. CBOW 아키텍쳐로 설계된 W2V 모델이 제대로 작동한다면, 두 맥락에서 모두 '부정선거'를 예측해야 합니다. 그런데 그러려면, 두 가지 맥락이 비슷한 벡터로 표현되어야 하겠죠. 그리고 그러려면, '정권'과 '정부'가 완전히 동일하지는 않더라도 비슷한 숫자로 표현되어야 할 것입니다. 그래서 출력층 연산을 통해 '부정선거'에 둘 다 비슷하게 높은 확률을 부여할 테니까요. 

요컨대 이런 것입니다. W2V의 CBOW 버전은 기본적으로 맥락을 주면 중심 단어를 예측하는 모델입니다. 이를 잘 하기 위해서는 은닉층에서 맥락을 잘 파악해야 합니다. 그런데 은닉층이 하는 연산은 근본적으로 '단어마다 W에서 특정 행 가져오기'입니다. 이 연산 결과가 맥락을 잘 표현하려면, 용법상 비슷한 맥락으로 사용되는 단어에는 (그래서 우리가 '의미가 유사하다'고 인식하는 단어에는) 유사한 벡터를 할당해야 합니다. 반대의 경우에는 상이한 벡터로 출력해야 하고요. 그러니까 이 모델을 학습시키면 학습시킬수록, 즉 그것이 예측 작업을 잘 하게 되면 할 수록, 실제 우리의 자료에서 나타난 용법상 맥락을 반영하여 각 단어의 벡터가 W의 각 행에 저장되는 것입니다. 즉 **비슷한 맥락을 표현하면 비슷한 벡터로 표현되어야 하는데, 어떤 단어가 비슷한 맥락으로 사용된다는 말은 비슷한 의미작용을 한다는 뜻이기 때문에, 결국 각 단어가 용법상 의미를 반영한 벡터값을 얻게 되는거죠.**

CBOW 기반으로 이제까지 설명했지만, Skip-gram이 작동하는 이유도 (그러니까 Skip-gram 아키텍쳐로 구현된 신경망 모델을 학습시키면 W에 단어의 벡터 표현이 나오는 이유) 사실 본질적으로 동일합니다. 중심 단어로 맥락을 잘 예측하려면, 은닉층 변환에서 용법과 의미가 비슷한 단어는 비슷한 벡터로 표현하고 그렇지 않은 단어는 서로 다른 벡터로 표현해야 합니다. 앞선 예를 다시 적어봅시다. 

- '자유당 정권의 부정선거에 항의하는 시민들' [자유당, 정권, 부정선거, 항의, 시민]
- '자유당 정부의 부정선거에 항의하는 시민들' [자유당, 정부, 부정선거, 항의, 시민]

여기서 '정권'으로 '자유당'과 '부정선거'를 예측한다고 하죠. 이 모델은 '정부'가 들어가도 '자유당'과 '부정선거'를 잘 예측해야 합니다. 그러면 이 모델은 훈련을 통해 입력이 '정권'으로 들어갔을 때와 '정부'로 돌어갔을 때 둘 모두 은닉층 출력 벡터가 비슷한 벡터로 표현하도록 유도될 것입니다. 그리고 그건, W에서 정권에 해당하는 행과 정부에 해당하는 행에 유사한 벡터가 할당됨을 의미하지요. 그러니까, 성능이 고도화되면, W가 의미와 용법을 반영한 단어의 벡터 표현을 갖게 됩니다.

한발짝 떨어져서 생각해보면, 이것 역시 결국 언어의 분포 가설 (distributional hypothesis)이나 소쉬르의 차이의 테제를 활용한 접근이라고도 할 수 있습니다. 

저 두 이론이 말하는 것처럼 어떤 단어의 의미가 주변 단어에 의해 결정된다면, 우선 주변 단어를 알면 중심 단어를 알 수 있습니다. 왜냐하면 주변 단어는 해당 단어가 가져야 할 의미를 결정할 것이고, 우리는 보통 하나의 의미 작동을 일으키기 위해 엄청나게 많은 단어를 쓰지 않거든요. 예를 들어 '이런 끔찍한 일을 하다니 저는 정말 ?? 같이 못된 놈이야.'라는 문장이 있다고 합시다. ??는 분명 뭔가 끔찍하고 혐오스러운 의미 작용을 하는 단어가 되어야 하죠. 그러면 들어갈게 뻔합니다. '악마', '괴물', '쓰레기' 뭐 이런게 들어가겠죠. 예측할 수 있다는 말입니다. 

반대도 마찬가지입니다. 중심 단어를 알면 주변 단어를 알 수 있어야 합니다. 어떤 단어의 의미 작동이 완전히 자유롭지 않고, 이제까지의 역사에 의해 용법에 일정한 제한이 있다면, 즉 주로 표현하던 의미가 있다면, 한 단어의 주변에 올 단어가 제한적입니다. 예를 들어 '괴물'이라는 단어 주변에 오는 단어는 뭔가 부정적인 정서나 공포를 표현하는 단어들일 공산이 큽니다. '끔찍', '못된' 이런 단어가 오기 마련이지, '친절', '따뜻' 이런 단어는 주변에 좀처럼 나타나지 않는다는 말입니다. 

요컨대 언어의 분포 가설이나 소쉬르의 테제가 말이 된다면, 맥락 -> 중심 혹은 중심 -> 맥락 예측이 가능해야 합니다. 그리고 Word2Vec은 실제 그 성능을 끌어올립니다. 그 와중에 Word2Vec의 모델 구조 때문에 각 단어의 '용법상 의미를 반영한 표현'이 은닉층 가중치 행렬인 W에 담기는거죠. 

그래서 Word2Vec은 동시 발생 행렬같은 빈도 기반 접근과 동일하게 언어의 분포 가설에 근거해 있다고 볼 수 있습니다. 다만, 언어의 분포 가설을 '주변 단어 세기'로 활용한 것이 아니라, '주변 단어 혹은 중심 단어 예측하기'로 활용하고, 그것을 수행하는 모델의 파라미터를 단어의 밀집 벡터 표현으로 활용하고 있는 셈이죠. 앞선 장에서도 말했지만, 이 전환은 최신 모델들에도 여전히 유지되고 있습니다.

## 6. 파이토치를 통한 구현과 최적화 가능 지점

### 6.1. CBOW 구현

자 그럼 W2V을 구현해보도록 합시다. 일단 CBOW를 가장 기본적인 구도로 구현해보도록 할게요. 보통 word2vec을 구현하면, gensim을 활용하는 경우가 많습니다. 아마, 실제로 앞으로 구현하실 일이 있으시면 그쪽이 더 편하실겁니다. 그런데 여기서는 우리의 이해의 확장을 위해, pytorch로 구현하도록 하겠습니다. 사실 이 정도 모델은 굳이 gensim을 쓰지 않아도 구현하는 건 어렵지 않습니다. 다만 속도는 좀 느릴 수 있지만요. 

자 구현을 위해서는 데이터가 필요한데, 이건 한국어 말뭉치 중 유명한 Naver sentiment movie corpus v1.0을 활용하겠습니다. 네이버 영화 리뷰에 정서 분류 레이블을 붙여놓은 데이터이죠. 여러 용도로 활용될 수 있는데, 여기서는 W2V 학습용으로 써보겠습니다. 이 데이터는 https://github.com/e9t/nsmc 이곳에 직접 방문하셔서 다운로드 받으시면 됩니다. "ratings_train.txt"가 실습에 사용될 파일입니다. 

자 그러면 일단 필요한 라이브러리를 읽어와 볼게요. 일단 아래 파트에서 오류가 나지 않아야 합니다. "mind-nlp-deep-cpu" 혹은 "mind-nlp-deep-gpu" 환경에서 작업하고 계시다면, 오류가 나지 않을 것입니다. 다만 print("DEVICE:", DEVICE) 라는 명령에 나오는 게 전자는 cpu일 태고, 후자는 cuda일 것입니다.

In [1]:
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from kiwipiepy import Kiwi

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("DEVICE:", DEVICE)

DEVICE: cuda

이제 데이터를 읽고 한 번 살펴봅시다.

In [2]:
df = pd.read_csv("ratings_train.txt", sep="\t") # 이 파일을 다운받으셨다고 가정하겠습니다. 
print(df.head())
print(df.shape)
print(df.columns)

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
(150000, 3)
Index(['id', 'document', 'label'], dtype='object')

재미있는 데이터죠? 맨 마지막 label 열은 positive - 1 negative - 0으로 잡혀 있습니다. 자세한 사항은 깃허브 페이지  https://github.com/e9t/nsmc 를 참조하세요. 

자 그런데 우리가 W2V을 학습시켜야 하니, 사실 document라는 열이 가장 중요합니다. 그 열이 비어 있는 행은 제외하고, 또 가능하면 리뷰가 너무 짧지 않았으면 하니, 공백포함 20글자 이하는 제외하겠습니다. 그리고 사실 지금 파이토치를 활용한 구현은 아주 빠르지는 않아서, 딱 5000개만 남기고 랜덤하게 뽑아보겠습니다. 다만, 여러분과 제가 결과가 동일해야 하니, seed를 이용해서 결과를 통일하겠습니다.

In [3]:
# document 결측 제거
df = df.dropna(subset=["document"]).copy()

# 너무 짧은 리뷰 제거
df = df[df["document"].str.len() > 20].copy()

# 실습용 샘플링
df_sample = df.sample(n=5000, random_state=42)

print(df_sample.shape)
df_sample.head()

(5000, 3)

             id                                           document  label
138931  3731672                             이 영화에 대한 이야기가 왜 이렇게 없냐      1
57620   9837177             아이들을 위한 영화인데, 재미있다! 유치하지만 코믹하고 감동도 있다!      1
96616   8474006  이 영화 한편으로 잘못된 생각을 가질지도 모를 수많은 이들..그리고 그로부터 생겨날...      0
14787   8226645  "처음엔 ""오로라 공주"" 제목두 상큼한 느낌이라 재밋을꺼 같았는데.. 마침표 찍...      0
50970   7502628        확실히 다른건 별로더라도, 한층더 진화된 시각적효과와 살해방법은 기상천외하다.      1

그리고 우리가 5장에서 배웠듯이, 이대로 분석을 할 수 없고 토큰화를 해야 합니다. 우리는 앞에서 배운 한글형태소 분석기 Kiwi를 활용하겠습니다. 다만 모든 품사에 해당하는 형태소를 다 쓰면 별로이니 (예를 들어 구두점 같은건 없는게 좋겠죠?) 명사, 동사, 형용사, 부사만 활용하겠습니다.

In [4]:
kiwi = Kiwi()

# 남길 품사
allowed_tags = {"NNG", "NNP", "VV", "VA", "MAG"}

def tokenize_with_kiwi(text):
    tokens = []
    analyzed = kiwi.tokenize(text)
    
    for tok in analyzed:
        if tok.tag in allowed_tags:
            token = tok.form
            if token:
                tokens.append(token)
    return tokens

# 토큰화
df_sample["tokens"] = df_sample["document"].apply(tokenize_with_kiwi)

print(df_sample.shape)
df_sample[["document", "tokens"]].head()

(5000, 4)

,document,tokens
138931,이 영화에 대한 이야기가 왜 이렇게 없냐,"[영화, 대하, 이야기, 왜, 없]"
57620,"아이들을 위한 영화인데, 재미있다! 유치하지만 코믹하고 감동도 있다!","[아이, 위하, 영화, 재미있, 코믹, 감동, 있]"
96616,이 영화 한편으로 잘못된 생각을 가질지도 모를 수많은 이들..그리고 그로부터 생겨날...,"[영화, 잘못, 생각, 가지, 모르, 수많, 생겨나, 피해, 생각, 주, 심정, 영..."
14787,"""처음엔 """"오로라 공주"""" 제목두 상큼한 느낌이라 재밋을꺼 같았는데.. 마침표 찍...","[처음, 오로라 공주, 제목, 느낌, 밋, 같, 마침표, 찍, 되, 이갸기, 꾸미,..."
50970,"확실히 다른건 별로더라도, 한층더 진화된 시각적효과와 살해방법은 기상천외하다.","[확실히, 다르, 별로, 한층, 더, 진화, 시각, 효과, 살해, 방법, 기상천외]"

자 그럼 우리 토큰화 결과가 리스트로 쌓였습니다. 이제 이들을 숫자로 전환하는 시스템을 위해 Vocab을 만들어볼게요. 늘 말씀드렸듯 핵심은 토큰과 숫자를 왔다갔다 할 수 있도록 하는 체계를 만드는 것입니다. 그 이외의 정보로, 전체 토큰 숫자나 토큰 별 빈도를 알고 있으면 좋겠죠. 

아마도 좀 의아하실 부분은 'unk' 라는 특수 토큰일 것 같네요. 이건 unknown, 즉 미지의 토큰이라는 의미입니다. 사실 Word2Vec이 학습 데이터 이외에 새로운 데이터를 받아서 뭔가 예측을 하는 일은 없어서, 직접 사용되지는 않습니다만, 여기서는 '저빈도 단어'를 처리하기 위한 용도로 사용할 예정입니다. 전체 데이터에서 너무 적게 사용되는 단어가 있으면 그게 노이즈가 되는 경우가 많습니다. 그래서, 일정 수준 이하의 빈도로 사용된 단어는 그냥 일괄되게 unk로 바꿀 예정입니다. 그냥 빼면 되지 않나 싶지만, 그냥 빠지면 맥락 거리 계산에도 영향을 미치기에, 그냥 저빈도 단어로 일괄 처리할 예정입니다. 

아래의 사전 클래스는, 일단 데이터를 보고 빈도를 계산한 다음, 거기서 저빈도 단어를 제외하고 사전을 만드는 동작을 하기 위해 설정되었습니다. 찬찬히 읽어보시면 잘 이해되실 겁니다.

In [5]:
UNK_token = 0
UNK_symbol = "<unk>"

class Vocab:
    def __init__(self, name=""):
        self.name = name
        self._word2count = {UNK_symbol: 0}
        self._word2index = {UNK_symbol: UNK_token}
        self._index2word = {UNK_token: UNK_symbol}
        self._n_words = 1

    def get_words(self):
        return list(self._word2count.keys())

    def num_words(self):
        return self._n_words

    def word2index(self, word):
        return self._word2index.get(word, self._word2index[UNK_symbol])

    def index2word(self, idx):
        return self._index2word[idx]

    def get_word_count(self, word):
        return self._word2count[word]

    def count_word(self, word):
        if word not in self._word2count:
            self._word2count[word] = 1
        else:
            self._word2count[word] += 1

    def build_vocab(self, min_count=1):
        self._word2index = {UNK_symbol: UNK_token}
        self._index2word = {UNK_token: UNK_symbol}
        self._n_words = 1

        for word, count in self._word2count.items():
            if word == UNK_symbol:
                continue
            if count >= min_count:
                self._word2index[word] = self._n_words
                self._index2word[self._n_words] = word
                self._n_words += 1

자 그럼 우리가 만들어 둔 데이터를 순회하면서 어휘 사전을 만들어보겠습니다. 우리가 만들어둔 사전 클래스가 기본적으로 count_word 라는 메서드를 통해 토큰별 빈도를 세어보고 그 결과에 기반하여 사전을 만듭니다. 그걸 아래와 같이 표현합니다.

In [6]:
W2V_VOCAB = Vocab(name="NSMC")

for sen in df_sample["tokens"]:
    for word in sen:
        W2V_VOCAB.count_word(word)

W2V_VOCAB.build_vocab(min_count=5)

print("Vocab size:", W2V_VOCAB.num_words())
print("Example words:", W2V_VOCAB.get_words()[:10])

Vocab size: 1505
Example words: ['<unk>', '영화', '대하', '이야기', '왜', '없', '아이', '위하', '재미있', '코믹']

이제, 토큰과 숫자를 오갈 시스템이 만들어졌습니다. 그 다음에 할 일은, CBOW용 '문제'를 만드는 것입니다. 자 그냥 문장이나 리뷰만 있다고 해서, 그걸로 Word2Vec을 학습시킬 수는 없습니다. 물론 gensim 같은 라이브러리를 활용하면 할 수 있지만, 지금은 우리가 신경망 모델을 직접 만들고 있으니 안됩니다. 뭐가 필요하냐? "맥락단어 -> 중심단어" 라는 형태의 문제와 정답이 필요합니다. 앞서 말씀드린 것처럼, 자기지도학습(self-supervised learning)을 위해 문제-정답 쌍을 준비하는 것이죠.  

여기서는 이걸 아래와 같은 방식의 데이터 정리를 진행하겠습니다. 예를 들어 앞에서 예로 든 것처럼 이런 문장과 토큰화가 있다고 하죠. 

- "1960년 자유당 정권의 부정선거에 항의하는 시민들을 향한 경찰의 발포로 16명이 희생된 3·15의거와 관련해 정부 차원의 공식 사과는 이번이 처음이다."(<이 대통령, ‘3·15의거’ 희생자·유가족에 “진심 어린 사과·위로”>, 경향신문, 2026년 3월 15일)
- 토큰화 자료입니다 [1960년, 자유당, 정권, 부정선거, 항의, 시민, 향한, 경찰, 발포, 16명, 희생, 3·15의거, 관련, 정부, 차원, 공식, 사과, 이번, 처음].

자 그리고 window가 2인 CBOW를 만든다고 하겠습니다. 그러면, 이런 식이 될 것입니다. 예를 들어 [1960년, 자유당, 부정선거, 항의]라는 단어 세트가 들어가면, '정권'을 예측해야 합니다. 한 칸 옆으로 가서 [자유당, 정권, 항의, 시민] 이 들어가면, '부정선거'를 예측해야죠. 

즉 우리의 문제와 정답은 ([맥락 단어들], 중심 단어) 라는 형태로 정리될 수 있습니다. 물론, 여기서 단어들은 모두 숫자로 전환해야겠지요. 이를 위해 CBOW_VOCAB을 만들었습니다. 저는 이를 위해 아래와 같은 함수를 활용하겠습니다.

In [7]:
def prep_cbow_data(token_lists, vocab, window=2):
    data_out = []

    for tokens in token_lists:
        token_num = len(tokens)

        if token_num < window * 2 + 1:
            continue

        for idx in range(window, token_num - window):
            left_context = tokens[idx - window: idx]
            right_context = tokens[idx + 1: idx + window + 1]
            context = left_context + right_context

            context_index = [vocab.word2index(word) for word in context]
            y_index = vocab.word2index(tokens[idx])

            data_out.append((context_index, y_index))

    return data_out

CBOW_DATA = prep_cbow_data(df_sample["tokens"], W2V_VOCAB, window=2)

print("len dataframe =", len(df_sample))
print("len CBOW data =", len(CBOW_DATA))
print(CBOW_DATA[:5])

len dataframe = 5000
len CBOW data = 33124
[([1, 2, 4, 5], 3), ([6, 7, 8, 9], 1), ([7, 1, 9, 10], 8), ([1, 8, 10, 11], 9), ([1, 12, 14, 15], 13)]

코드를 보시면 아시겠지만, 매우 간단한 구조입니다. 그냥 한칸씩 이동하면서 그때그때마다 문제를 만들고 있는거죠. 이 문제를 잘 해결하는 모델을 만들면, 각 단어의 좋은 벡터 표현이 나올 것입니다. 

그런 다음, 파이토치의 훈련 프로세스를 위해 Dataset 클래스를 설정합니다. 그리고 그것을 DataLoader라는 파이토치가 미리 만들어둔 클래스에 넣습니다. 10장에서 배운 것처럼 미니 배치를 만들어서 데이터 순회를 원활히 하기 위함입니다.  

여기서 하는 일이 하나 더 있지요. 지금 데이터는 단어들을 인덱스, 즉 그것이 몇 번째 단어인지 가리키는 방식으로 표현되고 있습니다. 그런데 우리가 앞에서 배운 것처럼, 처음에 신경망 모델에 정보가 입력될 때 원핫 벡터 형태여야 합니다. 특히 입력 데이터가 그렇죠. 출력쪽은, '몇 번째가 정답이다'라는 정보만 있으면 손실이 계산될 수 있으니 원핫 벡터가 될 필요가 없지만, 입력쪽은 은닉층 가중치 행렬이 곱해져야 하므로 원핫 벡터 형태여야 합니다. 그래서 그 절차가 들어가 있습니다.

In [8]:
import torch.nn.functional as F
   
class CBOWDataset_OneHot(Dataset):
    def __init__(self, data, vocab_size):
        self.data = data
        self.vocab_size = vocab_size
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        context, target = self.data[idx]
        
        context_tensor = torch.tensor(context, dtype=torch.long)
        context_onehot = F.one_hot(context_tensor, num_classes=self.vocab_size).float()
        
        target_tensor = torch.tensor(target, dtype=torch.long)
        
        return context_onehot, target_tensor


dataset = CBOWDataset_OneHot(CBOW_DATA, W2V_VOCAB.num_words())
dataloader = DataLoader(dataset, batch_size=128, shuffle=True)

# shape 확인
x_example, y_example = next(iter(dataloader))
print("x_example shape:", x_example.shape)  # [batch_size, context_size, vocab_size]
print("y_example shape:", y_example.shape)  # [batch_size]

x_example shape: torch.Size([128, 4, 1505])
y_example shape: torch.Size([128])

자 그러면 CBOW 모델을 선언해봅시다. 사실 매우 간단한 모델이라 파이토치 같은 딥러닝 전용 라이브러리를 쓰면 아래와 같이 매우 간단히 적을 수 있습니다. 두 개의 linear layer를 동원하면 되죠. 다만 편향을 끄는 것을 주의해야 합니다. 기본적으로 nn.Linear가 구현하는 linear layer는 편향을 더하는게 기본으로 잡혀 있는데, 지금 우리가 앞서 설명한 Word2Vec에서 은닉층과 출력층 변환은 그냥 W와 W'을 곱해주는 것만 있죠. 그래서 그걸 끄는 것입니다.

In [9]:
class CBOW_Linear(nn.Module):
    def __init__(self, vocab_size, embed_size):
        super().__init__()       
        # bias=False -> 편향이 없게 세팅
        self.linear1 = nn.Linear(vocab_size, embed_size, bias=False)
        self.linear2 = nn.Linear(embed_size, vocab_size, bias=False)

    def forward(self, x):
        # x: (batch_size, context_size, vocab_size)

        # 1. 각 context word 변환
        x_proj = self.linear1(x)  
        # (batch, context_size, embed_size)

        # 2. 평균
        h = x_proj.mean(dim=1)  
        # (batch, embed_size)

        # 3. 출력
        out = self.linear2(h)  
        # (batch, vocab_size)

        return out

자 그럼 모든 준비가 끝났습니다. 모델의 세팅을 제어하면서 시작해봅시다. 일단 임베딩 사이즈, 즉 각 단어를 몇 차원 공간의 벡터로 전환할 것인지 결정합니다. 이 실습에서는 50으로 설정하겠습니다. 너무 크면 너무 느립니다^^ 그리고 손실 함수는 cross entropy로 설정하고요, 최적화 알고리즘은 adam을 설정하겠습니다.

In [10]:
embed_size = 50

cbow_model = CBOW_Linear(W2V_VOCAB.num_words(), embed_size).to(DEVICE)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(cbow_model.parameters(), lr=0.002)

cbow_model

C:\Users\beama\anaconda3\envs\mind-nlp-deep-gpu\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

CBOW_Linear(
  (linear1): Linear(in_features=1505, out_features=50, bias=False)
  (linear2): Linear(in_features=50, out_features=1505, bias=False)
)

아래는 실제 훈련 루프용 함수입니다. 간단합니다. 그냥 데이터에서 문제와 정답 꺼내와서, 정답과 대비하면서 손실 계산하고, 역전파로 그레디언트 계산하고, 최적화 알고리즘으로 파라미터 업데이트를 합니다. 그 과정에서 중간중간에 프린트로 현황 보고 해주고요. 그리고 에폭별로 계산된 배치당 평균 손실값을 리스트에 넣어서 출력해주도록 했습니다. 향후에 활용하는 경우가 있거든요 (그래프를 그린다거나).

In [11]:
def train_cbow(model, dataloader, num_epochs, criterion, optimizer):
    all_epoch_losses = []

    total_batches = len(dataloader)
    print_interval = max(1, total_batches // 5)
    total_data_len = len(dataloader.dataset)

    for epoch in range(1, num_epochs + 1):
        model.train()
        epoch_losses = []

        for batch_idx, (x, y) in enumerate(dataloader, 1):
            x, y = x.to(DEVICE), y.to(DEVICE)

            y_hat = model(x)
            loss = criterion(y_hat, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            loss_value = loss.item()
            epoch_losses.append(loss_value)

            if batch_idx % print_interval == 0 or batch_idx == total_batches:
                current_data = batch_idx * dataloader.batch_size
                print(f"{min(current_data, total_data_len)}/{total_data_len} — loss: {loss_value:.4f}")

        avg_loss = sum(epoch_losses) / len(epoch_losses)
        all_epoch_losses.append(avg_loss)
        print(f"[Epoch {epoch}] Average Loss: {avg_loss:.4f}")

    return all_epoch_losses

In [12]:
losses = train_cbow(
    cbow_model,
    dataloader,
    num_epochs=10,
    criterion=criterion,
    optimizer=optimizer
)

6528/33124 — loss: 7.1194
13056/33124 — loss: 6.4412
19584/33124 — loss: 5.7884
26112/33124 — loss: 5.6120
32640/33124 — loss: 5.8728
33124/33124 — loss: 5.6186
[Epoch 1] Average Loss: 6.2270
6528/33124 — loss: 5.3718
13056/33124 — loss: 5.4872
19584/33124 — loss: 5.8919
26112/33124 — loss: 5.3657
32640/33124 — loss: 5.5914
33124/33124 — loss: 5.6663
[Epoch 2] Average Loss: 5.5420
6528/33124 — loss: 5.4704
13056/33124 — loss: 5.6089
19584/33124 — loss: 5.2512
26112/33124 — loss: 5.6796
32640/33124 — loss: 5.6672
33124/33124 — loss: 5.6622
[Epoch 3] Average Loss: 5.4704
6528/33124 — loss: 5.1935
13056/33124 — loss: 5.3432
19584/33124 — loss: 5.3856
26112/33124 — loss: 5.3016
32640/33124 — loss: 5.5775
33124/33124 — loss: 5.4408
[Epoch 4] Average Loss: 5.4249
6528/33124 — loss: 5.2081
13056/33124 — loss: 5.5455
19584/33124 — loss: 5.5915
26112/33124 — loss: 5.4974
32640/33124 — loss: 5.7806
33124/33124 — loss: 5.2699
[Epoch 5] Average Loss: 5.3804
6528/33124 — loss: 5.2210
13056/33124 — loss: 5.6371
19584/33124 — loss: 5.4265
26112/33124 — loss: 5.1854
32640/33124 — loss: 5.5151
33124/33124 — loss: 5.0489
[Epoch 6] Average Loss: 5.3272
6528/33124 — loss: 5.3171
13056/33124 — loss: 5.2429
19584/33124 — loss: 5.2883
26112/33124 — loss: 5.3913
32640/33124 — loss: 4.9157
33124/33124 — loss: 5.3175
[Epoch 7] Average Loss: 5.2676
6528/33124 — loss: 5.4916
13056/33124 — loss: 5.2772
19584/33124 — loss: 4.9404
26112/33124 — loss: 5.2792
32640/33124 — loss: 5.2680
33124/33124 — loss: 5.4963
[Epoch 8] Average Loss: 5.2031
6528/33124 — loss: 4.9774
13056/33124 — loss: 5.3278
19584/33124 — loss: 5.0787
26112/33124 — loss: 4.9221
32640/33124 — loss: 5.4407
33124/33124 — loss: 5.2089
[Epoch 9] Average Loss: 5.1353
6528/33124 — loss: 5.1958
13056/33124 — loss: 5.2436
19584/33124 — loss: 5.0521
26112/33124 — loss: 5.1806
32640/33124 — loss: 4.9695
33124/33124 — loss: 5.2852
[Epoch 10] Average Loss: 5.0639

전체적으로 로스가 떨어지는걸 보니 학습이 잘 진행되는거 같네요. 일단 이 정도로 해둡시다. 모델의 학습 종료 조건은 설정하기 나름이지만, 일단은 10 epoch 동안만 학습시키는 것으로 할게요. 

그런데 우리가 이걸 한 이유가 뭐죠? Word2Vec은 본질적으로 '단어의 벡터 표현'을 얻으려는 것이었습니다. 그건 어디있었죠? 첫번째 가중치 행렬에 있었습니다. 이건 파이토치에서 첫번째 linear layer로 구현되었죠. 그래서 거기서 가중치를 가져올 것입니다. 그리고 그게 우리 단어의 벡터 표현입니다.

In [13]:
embedding_matrix = cbow_model.linear1.weight.detach().cpu().T
print(embedding_matrix.shape)   # [vocab_size, embed_size]

torch.Size([1505, 50])

가져온 가중치 행렬이 딱 그렇게 생겼죠? 각 단어의 벡터 표현이 50 차원 공간의 벡터로 각 행에 저장되어 있습니다. 

자 그러면, 여기서 단어의 벡터 표현을 가져오려면 어떻게 하면 될까요? 간단합니다. 그 단어가 몇 번째 단어인지 가져와서, 그 순서의 행을 가져오면 됩니다. 아래처럼 말이죠.

In [14]:
def get_word_vector(word, vocab, embedding_matrix):
    idx = vocab.word2index(word)
    return embedding_matrix[idx]

word = "감동"
vec = get_word_vector(word, W2V_VOCAB, embedding_matrix)
print(word, vec[:10], vec.shape)  # 앞 10개만 보기

감동 tensor([ 0.5893,  0.1582,  0.4149, -0.5600, -0.2196, -0.7768,  0.7388, -0.0255,
        -0.2311,  0.5486]) torch.Size([50])

자 그러면 이 단어가 어떤 단어와 비슷하게 판정되었는지 살펴봅시다. 그러면 학습이 잘 되었는지 감을 잡을 수 있습니다.

In [15]:
import torch.nn.functional as F

def most_similar(word, vocab, embedding_matrix, topn=10):
    if word not in vocab._word2index:
        return f"'{word}' not in vocab."

    idx = vocab.word2index(word)
    query_vec = embedding_matrix[idx].unsqueeze(0)  # [1, embed_size]

    sims = F.cosine_similarity(query_vec, embedding_matrix, dim=1)
    sims[idx] = -1.0  # 자기 자신 제외

    top_indices = torch.topk(sims, topn).indices.tolist()
    return [(vocab.index2word(i), float(sims[i])) for i in top_indices]

most_similar("감동", W2V_VOCAB, embedding_matrix, topn=10)

[('전체', 0.7742792367935181),
 ('의미', 0.7727058529853821),
 ('교훈', 0.752139687538147),
 ('크', 0.7388326525688171),
 ('그야말로', 0.7318251132965088),
 ('특이', 0.7292410135269165),
 ('의문', 0.7262033224105835),
 ('딱히', 0.7225807309150696),
 ('스릴', 0.7163337469100952),
 ('메세지', 0.7141944766044617)]

어떤가요? 데이터가 작아 결과가 그리 좋지 않은 듯하지만, 일부는 아예 말이 되지 않는건 아닌 듯합니다. 사실 코드를 여러 셀에 걸쳐 작성하긴 했지만, 대부분 '분석을 준비하는' 단계를 위한 것이었고, 핵심 코드는 매우 단순했습니다. CBOW 모델 자체가 매우 단순하다는 말입니다. 그런데 부분적으로는 말이 되는 결과를 주고 있습니다. 데이터가 많아져서 학습의 정보가 많아지면 더욱 좋아질 것입니다.

### 6.2. look-up table로 최적화 하기 (앞서 말한 '행 고르기'의 구현)

자 그런데, 지금은 사실 5000개의 데이터만 갖고 하니 답답하지만 참고 기다릴 만 하지만, 데이터가 커지면 속도가 현저히 느려질 수 밖에 없습니다. GPU를 동원해도, 데이터가 커지면 느린건 마찬가지입니다. 그래서 명령을 실행하는 구조 상 뭔가를 개선할 수 있다면 참 좋을 것입니다. 즉 작업 구조를 최적화 할 수 있으면 좋겠다는 말입니다. 

가장 쉽게 할 수 있는 부분이 있습니다. 그건 바로, CBOW의 은닉층 연산을 실제 행렬 곱이 아니라, '행 고르기'로 만드는 것입니다. 제가 여러번, 첫번째 은닉층에서 일어나는 연산, 원핫벡터와 가중치 행렬이 곱해지는 연산은 본질적으로 행 고르기라고 말씀드렸습니다. 사실 Word2Vec을 구현하는 스타일이 여러가지라 가중치 행렬의 행이 아닌 열 고르기가 될 때도 있지만, 어쨌든 본질은 해당 단어에 해당하는 벡터를 호출하는 것입니다. 그게 실제 필요한 연산이라는 말이죠. 

게다가 파이토치는 이를 위한 전용 레이어를 구현하고 있습니다. nn.Embedding 이 그것인데요 자세한 설명은 괄호 안 링크를 읽어보시면 됩니다 (https://docs.pytorch.org/docs/stable/generated/torch.nn.Embedding.html). 간단히 말하자면, 이 레이어는 인덱스를 주면, 거기에 해당하는 정해진 길이의 벡터값을 출력해줍니다. 일종의 look-up table로 작동하는거죠. 그리고 이 벡터값들을 역전파 알고리즘에 따라 학습 가능하도록 하고 있습니다. 정확히 우리에게 필요한 두 가지, 우리가 설명에서 '행 고르기'라고 표현했던 연산과 (순전파) 그 값의 학습 (역전파) 을 가능하게 하고 있다는 말입니다. 

이걸 활용하면, 속도가 개선되는 것을 바로 느끼실 수 있습니다. 그럼, 그것만 개선해보겠습니다. 정확히는 그거 때문에 바뀌는 부분이 약간 있긴 한데, 본질적으로는 비슷합니다.

일단 앞에서 정리해 둔 데이터는 그대로 모두 쓰겠습니다. df_sample["tokens"], CBOW_DATA와 W2V_VOCAB이 우리가 전처리를 거쳐 만든 핵심 정보인데, 이건 바뀔게 없습니다.

다만 Dataset을 만드는 방식이 좀 바뀝니다. 이 부분을 간략히 할 수 있습니다. 왜냐하면 입력 데이터를 원핫 벡터로 전환할 필요가 없어지기 때문입니다. nn.Embedding이라는 레이어로 첫번째 선형 변환 레이어를 대체할 것인데, nn.Embedding은 그냥 인덱스를 입력으로 받습니다. 그러니 굳이 vocab에 근거하여 단어를 인덱스 숫자로 바꾼 후, 다시 그걸 원핫벡터로 바꿀 필요가 없습니다. 아래와 같이 단순화 가능합니다.

In [16]:
class CBOWDataset(Dataset):
    def __init__(self, data):
        self.data = data
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        context, target = self.data[idx]
        
        context_tensor = torch.tensor(context, dtype=torch.long)       
        target_tensor = torch.tensor(target, dtype=torch.long)
        
        return context_tensor, target_tensor


dataset = CBOWDataset(CBOW_DATA)
dataloader = DataLoader(dataset, batch_size=128, shuffle=True)

# shape 확인
x_example, y_example = next(iter(dataloader))
print("x_example shape:", x_example.shape)  # [batch_size, context_size]
print("y_example shape:", y_example.shape)  # [batch_size]

x_example shape: torch.Size([128, 4])
y_example shape: torch.Size([128])

그리고 결정적으로 본 모델 클래스가 이렇게 단순화되죠. 달라진 부분은 첫번째 선형 변환층을 nn.Embedding으로 바꾼 것입니다.

In [17]:
class CBOW(nn.Module):
    def __init__(self, vocab_size, embed_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.linear_layer = nn.Linear(embed_size, vocab_size, bias=False)

    def forward(self, x):
        # x: [batch_size, context_size]
        x_embed = self.embedding(x)              # [batch_size, context_size, embed_size]
        x_mean = x_embed.mean(dim=1)             # [batch_size, embed_size]
        out = self.linear_layer(x_mean)          # [batch_size, vocab_size]
        return out

그럼 나머지 파트도 동일합니다.

In [18]:
embed_size = 50

cbow_model_2 = CBOW(W2V_VOCAB.num_words(), embed_size).to(DEVICE)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(cbow_model_2.parameters(), lr=0.002)

def train_cbow(model, dataloader, num_epochs, criterion, optimizer):
    all_epoch_losses = []

    total_batches = len(dataloader)
    print_interval = max(1, total_batches // 5)
    total_data_len = len(dataloader.dataset)

    for epoch in range(1, num_epochs + 1):
        model.train()
        epoch_losses = []

        for batch_idx, (x, y) in enumerate(dataloader, 1):
            x, y = x.to(DEVICE), y.to(DEVICE)

            y_hat = model(x)
            loss = criterion(y_hat, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            loss_value = loss.item()
            epoch_losses.append(loss_value)

            if batch_idx % print_interval == 0 or batch_idx == total_batches:
                current_data = batch_idx * dataloader.batch_size
                print(f"{min(current_data, total_data_len)}/{total_data_len} — loss: {loss_value:.4f}")

        avg_loss = sum(epoch_losses) / len(epoch_losses)
        all_epoch_losses.append(avg_loss)
        print(f"[Epoch {epoch}] Average Loss: {avg_loss:.4f}")

    return all_epoch_losses


losses = train_cbow(
    cbow_model_2,
    dataloader,
    num_epochs=10,
    criterion=criterion,
    optimizer=optimizer
)

6528/33124 — loss: 6.8077
13056/33124 — loss: 6.2755
19584/33124 — loss: 6.2238
26112/33124 — loss: 5.7830
32640/33124 — loss: 5.8632
33124/33124 — loss: 6.2060
[Epoch 1] Average Loss: 6.3181
6528/33124 — loss: 5.6729
13056/33124 — loss: 5.2915
19584/33124 — loss: 5.5542
26112/33124 — loss: 5.5107
32640/33124 — loss: 5.5031
33124/33124 — loss: 5.8335
[Epoch 2] Average Loss: 5.5561
6528/33124 — loss: 5.5069
13056/33124 — loss: 5.1945
19584/33124 — loss: 5.5635
26112/33124 — loss: 4.9520
32640/33124 — loss: 5.2589
33124/33124 — loss: 5.1204
[Epoch 3] Average Loss: 5.3102
6528/33124 — loss: 5.1399
13056/33124 — loss: 5.2201
19584/33124 — loss: 5.2637
26112/33124 — loss: 5.1602
32640/33124 — loss: 5.1201
33124/33124 — loss: 5.2989
[Epoch 4] Average Loss: 5.1449
6528/33124 — loss: 4.7606
13056/33124 — loss: 5.2230
19584/33124 — loss: 5.1874
26112/33124 — loss: 5.0840
32640/33124 — loss: 4.6683
33124/33124 — loss: 4.7555
[Epoch 5] Average Loss: 5.0150
6528/33124 — loss: 4.8893
13056/33124 — loss: 4.9015
19584/33124 — loss: 4.9539
26112/33124 — loss: 4.6520
32640/33124 — loss: 4.8999
33124/33124 — loss: 4.6753
[Epoch 6] Average Loss: 4.9029
6528/33124 — loss: 4.7958
13056/33124 — loss: 5.0098
19584/33124 — loss: 4.8989
26112/33124 — loss: 4.9203
32640/33124 — loss: 4.5394
33124/33124 — loss: 4.9305
[Epoch 7] Average Loss: 4.8025
6528/33124 — loss: 4.6932
13056/33124 — loss: 4.5109
19584/33124 — loss: 4.8156
26112/33124 — loss: 4.9290
32640/33124 — loss: 5.0308
33124/33124 — loss: 5.3268
[Epoch 8] Average Loss: 4.7104
6528/33124 — loss: 4.7845
13056/33124 — loss: 4.5172
19584/33124 — loss: 4.5433
26112/33124 — loss: 4.5986
32640/33124 — loss: 4.8409
33124/33124 — loss: 4.6446
[Epoch 9] Average Loss: 4.6228
6528/33124 — loss: 4.3877
13056/33124 — loss: 4.2449
19584/33124 — loss: 4.5824
26112/33124 — loss: 5.0119
32640/33124 — loss: 4.5861
33124/33124 — loss: 4.6046
[Epoch 10] Average Loss: 4.5418

많은 경우 속도 변화를 체감하실 수 있을거라 생각합니다. 데이터가 커지면 이 변화도 함께 커지죠. 나머지 부분도 거의 동일한데, nn.Linear가 아니라 nn.Embedding으로 구현된 레이어에서 weight 정보를 가져와야 하니 그 부분만 명령이 약간 바뀝니다.

In [19]:
embedding_matrix_2 = cbow_model_2.embedding.weight.detach().cpu()
print(embedding_matrix_2.shape)   # [vocab_size, embed_size]

def get_word_vector(word, vocab, embedding_matrix):
    idx = vocab.word2index(word)
    return embedding_matrix[idx]

word = "감동"
vec = get_word_vector(word, W2V_VOCAB, embedding_matrix_2)
print(word, vec[:10], vec.shape)  # 앞 10개만 보기

import torch.nn.functional as F

def most_similar(word, vocab, embedding_matrix, topn=10):
    if word not in vocab._word2index:
        return f"'{word}' not in vocab."

    idx = vocab.word2index(word)
    query_vec = embedding_matrix[idx].unsqueeze(0)  # [1, embed_size]

    sims = F.cosine_similarity(query_vec, embedding_matrix, dim=1)
    sims[idx] = -1.0  # 자기 자신 제외

    top_indices = torch.topk(sims, topn).indices.tolist()
    return [(vocab.index2word(i), float(sims[i])) for i in top_indices]

most_similar("감동", W2V_VOCAB, embedding_matrix_2, topn=10)

torch.Size([1505, 50])
감동 tensor([ 0.5750, -0.6619,  0.2618,  1.6318,  0.3373, -1.7550, -0.6188,  0.8673,
        -2.4511, -0.1845]) torch.Size([50])

[('새끼', 0.45187243819236755),
 ('절반', 0.45036378502845764),
 ('좋아하', 0.44897258281707764),
 ('로맨틱', 0.4242340326309204),
 ('임팩트', 0.42294561862945557),
 ('떠오르', 0.4223434627056122),
 ('수작', 0.415630578994751),
 ('근래', 0.41229742765426636),
 ('시절', 0.4069075584411621),
 ('세련', 0.40501242876052856)]

### 6.3. Skip-gram 구현

자 그러면 다음으로 skip-gram을 구현해봅시다. 이것도 거의 동일합니다. 전처리 파트, 예를 들어 토큰화나 사전 형성 과정은 달라질게 없죠. 

다만, 문제가 중심 -> 맥락으로 바뀌니, 주어진 언어 자료에서 문제-정답 쌍을 가져오는 방식이 달라져야 합니다. 그리고 그것 말고 딱히 달라질 게 없습니다. 

역시 변치 않는 것은 전처리 결과가 있습니다. df_sample["tokens"]과 W2V_VOCAB 이죠. 이건 그대로 쓰겠습니다. 

다만 문제 생성 방식이 바뀌니 Skipgram_DATA를 새로 만들어야 할 것입니다. 그건 아래와 같이 가능합니다. prep_cbow_data 대신 prep_skip_gram_data 라는 함수를 만들어봤습니다.

In [20]:
def prep_skip_gram_data(token_lists, vocab, window=2):

    data_out = []

    for tokens in token_lists:
        token_num = len(tokens)

        if token_num < window * 2 + 1:
            continue

        for idx in range(window, token_num - window):
            center = vocab.word2index(tokens[idx])
            context = [vocab.word2index(x) for x in tokens[idx - window:idx] + tokens[idx + 1:idx + window + 1]]
            for context_word in context:
                data_out.append((center, context_word))

    return data_out

Skipgram_DATA = prep_skip_gram_data(df_sample["tokens"], W2V_VOCAB, window=2)
print(Skipgram_DATA[:10])

[(3, 1), (3, 2), (3, 4), (3, 5), (1, 6), (1, 7), (1, 8), (1, 9), (8, 7), (8, 1)]

자 skip-gram을 위해 문제-정답 쌍을 만드는 방법은 다양하지만, 여기서는 가장 간편한 방법을 선택했습니다. (중심 -> 맥락)이라는 문제와 정답 쌍을 맥락 단어마다 만드는 것입니다. 

코드를 보면 아시겠지만, 지금 저 코드는 아래와 같은 작업을 합니다. 
예를 들어 한 문서의 토큰이 다음과 같다고 가정합시다: ['오늘', '날씨', '맑음', '기온', '상승']
중심 단어가 '맑음'일 경우, 주변 단어(맥락 단어)는 앞뒤로 2개씩: ['오늘', '날씨', '기온', '상승']이 됩니다. 
Skip-gram에서는 이 중심 단어 '맑음'을 입력받아 주변 단어 '오늘', '날씨', '기온', '상승'을 예측할 수 있어야 합니다. 
그렇기에 우리의 문제-정답 쌍을 이렇게 네 개 만들 수 있습니다 : ('맑음', '오늘'), ('맑음', '날씨'), ('맑음', '기온'), ('맑음', '상승')

즉 하나의 중심 단어로부터 네 개의 문제를 만드는 것이지요. 앞에서 모델을 설명할 때에는 사실 CBOW와 대비하기 위해 네 개의 단어를 예측하고 평균 손실을 만들어서 모델을 갱신한다고 말씀드렸는데, 학습의 관점에서는 이렇게 정리해서 배치를 만들어서 넣어도 거의 동일한 효과가 납니다. 앞서 말씀드렸듯 지금 세팅에서는 미니 배치마다 평균 손실을 계산하여 역전파하는데, 이렇게 여러 문제 만들어서 넣으면 결과적으로 비슷한 효과를 낼 것입니다. 

즉 이 함수의 구현 목표는 이 쌍들을 숫자 인덱스로 변환한 뒤 각각을 튜플 (center_index, context_index)로 만들고 리스트에 차곡차곡 담아서 반환하는 것입니다. 이렇게 만들어진 각 튜플이 하나의 학습 샘플이 되는거죠. 최종 출력 예시는 아래와 같습니다: [(1, 3), (1, 7), (1, 6), ...]

나머지는 이제 비슷합니다. 데이터 셋 만들고, 모델 만들고 진행하면 됩니다. 아래 보시면 아시겠지만, 더 단순합니다. 특히 모델은, CBOW 때에는 맥락 단어들의 벡터를 평균 내는 과정이 생략되니 단순한 것이 더 단순해졌습니다^^ 나머지 훈련 루프나 벡터 뽑아내기는 더 단순하죠.

In [21]:
class SkipgramDataset(Dataset):
    def __init__(self, data):
        self.data = data
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        center, context = self.data[idx]
        
        center_tensor = torch.tensor(center, dtype=torch.long)       
        context_tensor = torch.tensor(context, dtype=torch.long)
        
        return center_tensor, context_tensor


dataset = SkipgramDataset(Skipgram_DATA)
dataloader = DataLoader(dataset, batch_size=128, shuffle=True)

# shape 확인
x_example, y_example = next(iter(dataloader))
print("x_example shape:", x_example.shape)  # [batch_size]
print("y_example shape:", y_example.shape)  # [batch_size]


class Skipgram(nn.Module):
    def __init__(self, vocab_size, embed_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.linear_layer = nn.Linear(embed_size, vocab_size, bias=False)

    def forward(self, x):
        x_embed = self.embedding(x)              # [batch_size, embed_size]
        out = self.linear_layer(x_embed)          # [batch_size, vocab_size]
        return out

x_example shape: torch.Size([128])
y_example shape: torch.Size([128])

In [22]:
embed_size = 50

Skipgram_model = Skipgram(W2V_VOCAB.num_words(), embed_size).to(DEVICE)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(Skipgram_model.parameters(), lr=0.002)

def train_Skipgram(model, dataloader, num_epochs, criterion, optimizer):
    all_epoch_losses = []

    total_batches = len(dataloader)
    print_interval = max(1, total_batches // 5)
    total_data_len = len(dataloader.dataset)

    for epoch in range(1, num_epochs + 1):
        model.train()
        epoch_losses = []

        for batch_idx, (x, y) in enumerate(dataloader, 1):
            x, y = x.to(DEVICE), y.to(DEVICE)

            y_hat = model(x)
            loss = criterion(y_hat, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            loss_value = loss.item()
            epoch_losses.append(loss_value)

            if batch_idx % print_interval == 0 or batch_idx == total_batches:
                current_data = batch_idx * dataloader.batch_size
                print(f"{min(current_data, total_data_len)}/{total_data_len} — loss: {loss_value:.4f}")

        avg_loss = sum(epoch_losses) / len(epoch_losses)
        all_epoch_losses.append(avg_loss)
        print(f"[Epoch {epoch}] Average Loss: {avg_loss:.4f}")

    return all_epoch_losses


losses = train_Skipgram(
    Skipgram_model,
    dataloader,
    num_epochs=10,
    criterion=criterion,
    optimizer=optimizer
)

26496/132496 — loss: 6.4312
52992/132496 — loss: 5.8592
79488/132496 — loss: 5.8813
105984/132496 — loss: 5.6749
132480/132496 — loss: 5.7779
132496/132496 — loss: 6.5459
[Epoch 1] Average Loss: 6.1809
26496/132496 — loss: 5.2257
52992/132496 — loss: 5.6846
79488/132496 — loss: 5.7984
105984/132496 — loss: 5.5963
132480/132496 — loss: 5.1173
132496/132496 — loss: 5.8910
[Epoch 2] Average Loss: 5.4740
26496/132496 — loss: 5.3321
52992/132496 — loss: 5.6462
79488/132496 — loss: 5.6002
105984/132496 — loss: 5.5810
132480/132496 — loss: 5.0445
132496/132496 — loss: 4.9910
[Epoch 3] Average Loss: 5.3418
26496/132496 — loss: 5.5380
52992/132496 — loss: 5.2263
79488/132496 — loss: 5.2103
105984/132496 — loss: 5.5594
132480/132496 — loss: 5.6762
132496/132496 — loss: 5.5473
[Epoch 4] Average Loss: 5.2802
26496/132496 — loss: 5.1022
52992/132496 — loss: 5.3065
79488/132496 — loss: 4.8688
105984/132496 — loss: 5.6535
132480/132496 — loss: 5.3390
132496/132496 — loss: 4.9850
[Epoch 5] Average Loss: 5.2349
26496/132496 — loss: 5.3779
52992/132496 — loss: 5.1753
79488/132496 — loss: 5.2988
105984/132496 — loss: 5.0881
132480/132496 — loss: 5.4078
132496/132496 — loss: 4.3448
[Epoch 6] Average Loss: 5.1962
26496/132496 — loss: 4.9300
52992/132496 — loss: 4.7248
79488/132496 — loss: 5.2901
105984/132496 — loss: 4.7064
132480/132496 — loss: 5.3104
132496/132496 — loss: 5.4747
[Epoch 7] Average Loss: 5.1642
26496/132496 — loss: 5.4511
52992/132496 — loss: 5.2497
79488/132496 — loss: 5.1170
105984/132496 — loss: 5.4109
132480/132496 — loss: 5.2348
132496/132496 — loss: 5.4845
[Epoch 8] Average Loss: 5.1336
26496/132496 — loss: 5.0942
52992/132496 — loss: 5.1758
79488/132496 — loss: 5.0477
105984/132496 — loss: 5.1322
132480/132496 — loss: 4.9844
132496/132496 — loss: 5.0800
[Epoch 9] Average Loss: 5.1055
26496/132496 — loss: 5.0571
52992/132496 — loss: 5.4915
79488/132496 — loss: 5.1612
105984/132496 — loss: 5.1771
132480/132496 — loss: 5.0254
132496/132496 — loss: 5.5823
[Epoch 10] Average Loss: 5.0801

여기서 잠깐! CBOW 때보다 케이스 수가 늘어난 것이 보이시죠? 당연합니다. CBOW 때에는 (여러 맥락 -> 중심) 이런 식으로 문제-정답 쌍을 만들었는데, 지금은 (중심 -> 맥락 1), (중심 -> 맥락 2)...이런 식으로 중심 단어 하나마다 윈도우 사이즈 x 2 만큼 문제-정답 쌍을 만들거든요. 그래서 훨씬 늘어났죠. 

그리고 케이스 수만 늘어난게 아니라, 사실 모델에게 요구되는 문제 풀이의 난이도가 늘어난 면이 있습니다. 왜냐하면 <여러 맥락 단어 -> 중심 단어>라는 문제는 단서가 많죠. 그래서 맞추기도 편합니다. 그런데 <중심 단어 -> 여러 맥락 단어>라는 문제는 단서는 줄어들었는데 할 일은 더 많은 상황입니다. 그래서 동일한 조건을 가정하면, CBOW 보다 Skip-gram 아키텍쳐가 모델에게 더 어려운 과제를 요구하는 면이 있습니다. 그래서 만약 데이터가 충분하다면, Skip-gram이 보다 더 세밀한 관계를 학습하는데 유리하다고 평가되는 경우도 있습니다.  

벡터 표현을 뽑는건 완전히 동일합니다.

In [23]:
embedding_matrix_3 = Skipgram_model.embedding.weight.detach().cpu()
print(embedding_matrix_3.shape)   # [vocab_size, embed_size]

def get_word_vector(word, vocab, embedding_matrix):
    idx = vocab.word2index(word)
    return embedding_matrix[idx]

word = "감동"
vec = get_word_vector(word, W2V_VOCAB, embedding_matrix_3)
print(word, vec[:10], vec.shape)  # 앞 10개만 보기

import torch.nn.functional as F

def most_similar(word, vocab, embedding_matrix, topn=10):
    if word not in vocab._word2index:
        return f"'{word}' not in vocab."

    idx = vocab.word2index(word)
    query_vec = embedding_matrix[idx].unsqueeze(0)  # [1, embed_size]

    sims = F.cosine_similarity(query_vec, embedding_matrix, dim=1)
    sims[idx] = -1.0  # 자기 자신 제외

    top_indices = torch.topk(sims, topn).indices.tolist()
    return [(vocab.index2word(i), float(sims[i])) for i in top_indices]

most_similar("감동", W2V_VOCAB, embedding_matrix_3, topn=10)

torch.Size([1505, 50])
감동 tensor([-0.4866, -1.6525, -0.8284, -0.1298,  0.9155, -0.5074, -0.1904, -2.1890,
         1.6030, -0.2729]) torch.Size([50])

[('느리', 0.4833497405052185),
 ('코미디', 0.45985347032546997),
 ('드라마', 0.45851248502731323),
 ('정보', 0.4522014558315277),
 ('남', 0.43205711245536804),
 ('우정', 0.41848134994506836),
 ('메세지', 0.418378621339798),
 ('땅', 0.4106646478176117),
 ('전체', 0.40950602293014526),
 ('허세', 0.4059489071369171)]

어떤가요? 쉽죠? 동일한 모델의 약간 다른 디자인이니 사실 바뀔 부분이 많지 않습니다.

### 6.4. Negative sampling으로 최적화 하기

#### 6.4.1. 출력층 연산의 핵심과 W'에 담기는 벡터 표현

마지막으로 하나의 최적화 장치를 추가해보겠습니다. Negative sampling이라는 기법이 그것입니다. 앞서 look-up table을 활용한 최적화가 은닉층 변환에서 계산 효율을 노린 것이라면, Negative sampling은 출력층 변환에서 계산 효율을 노린 것이라고 할 수 있습니다. 

현재 우리의 Word2vec 코드가 출력층에서 하는 변환을 생각해봅시다. 은닉층이 어떤 벡터를 출력합니다. 그건 우리가 설정한 목표 차원 공간에 존재하는 벡터입니다. 예를 들어 우리가 Word2vec을 통해 단어들을 100차원 공간의 벡터로 전환하기를 원했으면, 은닉층 출력 벡터 역시 100차원 공간의 벡터일 것입니다. 출력층에서는 이 100차원 공간의 벡터를 출력층 가중치 행렬인 W'과 곱하는 일이 일어납니다. W' 가중치 행렬은 (100, V) 라는 형태를 가질 것입니다. 즉 (우리가 설정한 차원수, 어휘수) 라는 형태를 가진다는 말입니다. 

이걸 하는 이유는, 최종적으로 단어 혹은 토큰 각각이 현재 과제에서 '정답'일 가능성을 계산하기 위함이었습니다. 즉 word2vec은 결국 어떤 단어가 정답인지 여부를 판단해야 하는 모델입니다. CBOW에서는 어떤 단어가 중심 단어인지 판단해야 하고, Skip-gram은 어떤 단어가 맥락 단어인지 판단해야 합니다. 이를 위해 모든 단어가 가지는 정답 확률을 산출하고 싶고, 그 기초 자료를 이런 행렬 연산을 통해 달성하려 했습니다. 위의 예를 계속 쓰자면, (1,100)으로 생긴 은닉층 출력 벡터를 (100, 어휘수)라는 W' 가중치 행렬에 곱해서 (1, 어휘수)라는 각 단어의 점수로 바꾸는 거죠. 그리고 이 점수는 은닉층 출력벡터를 W'의 각 칼럼과 dot product를 한 결과라고 할 수 있습니다. 그 결과가 각 단어의 점수가 되는거죠. 

여기서 소프트맥스 활성화함수가 적용되면, 최종적으로 우리는 Word2vec이 부여하는 문제에 대해 어떤 단어가 정답이 될지에 대한 확률 분포를 얻게 됩니다. 지금 문제로 주어진 단어 위치에 대한 일종의 단어 확률 분포를 얻는 셈이지요. 그리고 그 확률 분포에 기대어서 손실이 계산되고 (보통 cross-entropy를 사용하죠), 그 손실에 대해 가지는 각 파라미터의 미분 계수에 근거하여 모델이 계산됩니다. 

이런 과정을 통해 계산되기에, 사실 출력층 가중치 행렬 W'에도 또다른 단어별 벡터 표현이 담기게 됩니다. (100, 어휘수) 라는 형태를 가지게 되는 출력층 가중치 행렬의 각 열(column)은 각 단어의 벡터 표현이 될 수 있다는 말입니다. 원리는 W에 벡터 표현이 담기는 것과 비슷합니다. 우리의 Word2vec이 잘 작동한다면, 비슷한 맥락을 공유하는 단어는, 그래서 의미가 유사하다고 보는 단어는 벡터 표현이 유사해야 합니다. 앞서 든 예를 다시 들어보죠. CBOW 디자인을 가정하겠습니다. 

- '자유당 **정권**의 부정선거에 항의하는 시민들' [자유당, 정권, 부정선거, 항의, 시민]
- '자유당 **정부**의 부정선거에 항의하는 시민들' [자유당, 정부, 부정선거, 항의, 시민]

이 경우 [자유당, 부정선거]라는 맥락이 들어가면, '정권'도 그럴 듯하고, '정부'도 그럴 듯합니다. 실제로 우리의 직관에 따라서도 둘의 의미 작용은 비슷하죠. 그렇기에 [자유당, 부정선거]를 입력으로 받아 최종적으로 각 단어의 점수를 만들고 또 확률을 만들 때, 정권의 점수/확률과 정부의 점수/확률은 비슷하게 높게 나와야 합니다. 그런데 그러려면, 출력층 가중치 행렬 W'에서 각 단어에 해당하는 칼럼에 유사한 벡터 표현이 들어가야 합니다. 

계산 과정을 돌아보면 더 이해가 쉽습니다. [자유당, 부정선거]를 입력으로 받아 은닉층 출력 벡터가 만들어지면, 이것이 W'의 각 칼럼과 dot product를 산출합니다. 즉 W'의 각 칼럼은, 각 단어의 최종 점수를 산출하는 벡터인 셈입니다. 그런데 여러 단어 중 '정권'에 해당하는 점수와 '정부'에 해당하는 점수가 유사하게 나오고 동시에 높아야 한다면, W'에서 '정권'에 해당하는 점수를 산출하는 칼럼과 '정부'에 해당하는 칼럼을 산출하는 칼럼은 벡터 표현이 유사해야 합니다. 반대로, 엉뚱한 단어는 최종 확률이 낮아야 하기에, 유사하지 않은 벡터 표현을 가져야 합니다. 

요컨대, Word2Vec이 과제를 잘 해결하려고 학습이 되면, 결과적으로 출력층 가중치 행렬 W'에도 또다른 종류의 단어 벡터 표현이 남게 됩니다. 그리고 실제로 Word2vec 이후의 몇 가지 기법은 이 출력층 가중치 행렬의 벡터 표현을 활용하는 경우도 있었습니다.

#### 6.4.2. 정답 중심의 단순화와 거기에 따르는 문제

자 그런데, 이 출력층에서 일어나는 변환 연산은 계산 비용이 큽니다. 지금 설명한 것처럼 (1, 100) X (100, 어휘수) 가 일어나면, 이 연산은 100차원 공간의 벡터 두 개 사이의 dot product를 어휘수만큼 반복해야 합니다. 어휘수가 보통 엄청 많기 때문에 이건 비용이 큰 연산입니다. 다만 이건 각 단어의 점수, 즉 정답 확률 계산의 재료가 되는 점수를 계산하기 위해서는 어쩔 수 없는 면이 있지요. 

이걸 좀 더 효율화 할 수는 없을까요? '모든 단어'에 대해 점수를 계산하는 대신, '정답'에 해당하는 단어의 점수만 계산하면 어떨까요? 우리는 주어진 문서를에서 여러 개의 '문제-답' 쌍을 만들기 위해 노력했습니다. CBOW에서도 그랬고, Skip-gram에서도 그랬죠. 즉 모든 케이스에는 답이 이미 정해져 있습니다. 그럼 우리의 모델이 모든 단어의 점수를 계산하도록 하는 대신, 어떤 문제의 정답에 해당하는 단어의 점수만 계산하도록 하면 어떨까요? 그러니까 (1,100) X (100, 어휘수) 대신, 은닉층 출력 벡터인 (1,100)와 정답에 해당하는 단어에 해당하는 출력층 가중치 행렬의 열(column) 만 가져와서, dot product를 하는 것입니다. 

자 그러면 어휘 숫자 만큼의 점수 대신, 하나의 어휘, 즉 정답에 해당하는 어휘의 점수만 나올 것입니다. (1, 어휘수) 라는 벡터 대신, 그냥 숫자 하나만 주어지는 셈이죠. 이걸 확률 형식으로 변환하려면 어떻게 하면 좋을까요? 소프트맥스 대신 시그모이드 활성화 함수를 활용할 수 있습니다. 10장에서 배웠듯, 그것은 0과 1사이의 숫자로 변환해줄 것입니다. 사실 이걸 정확히 확률로 볼 수 있는지는 논의의 여지가 있지만, 일단 진행합시다. 그리고 이 확률에 기반한 손실을 cross-entropy를 통해 계산할 수 있습니다.

이렇게 하면 계산량은 획기적으로 줄어들 것입니다. 엄청 빨라지겠죠. 하지만 이렇게만 접근하면 중요한 문제가 생깁니다. **모델이 '정답'에 해당하는 단어를 유력하게 보도록 변화하도록 학습시킬 수는 있지만, 나머지 단어가 정답에 해당하지 않는다고 판단하도록 학습시키지는 못한다는 점입니다.** Word2vec의 기본 컨셉은, 우리가 부여하는 과제를 잘 수행하도록 학습시키면, 은닉층에 포함된 가중치 행렬 W가 단어의 훌륭한 벡터 표현을 가진다는 점에 있습니다. 그렇기에 여기서 핵심적인 전제는 학습이 잘 되어야 한다는 것입니다. 그런데 이처럼 결과적으로 정답에 해당하는 단어의 점수만 산출하고, 그것에만 근거하여 손실을 계산하면, 모델의 학습에 상당한 제한점이 생깁니다. 자연히 단어의 벡터 표현도 완성도가 떨어집니다.  

약간만 자세히 설명해볼게요. 원래 버전을 보죠. 즉 최적화하지 않고 소프트맥스를 써서 모든 단어에 대해 확률을 만들고 거기서 손실을 계산한다고 하겠습니다. 여기서 손실이 낮아지려면, 정답에 해당하는 단어의 확률이 올라가야 합니다. 그리고 정답 단어에 부여된 확률이 올라가려면 다른 단어들을 부여된 확률은 내려가야 합니다. 이는 정답에 해당하는 단어의 점수가 다른 단어의 점수보다 상대적으로 커야 한다는 점을 의미합니다. 소프트맥스는 결국 각 단어 점수들의 정규화 절차이니까요. 이런 세팅에서 손실에 근거하여 모델의 파라미터를 조정하면, 정답에 해당하는 단어의 점수는 높아지고 오답에 해당하는 단어들의 점수는 상대적으로 낮아지는 결과를 낳도록 모델이 조정될 공산이 큽니다. 이를 위해서는 우선 출력층 가중치 행렬의 모든 성분의 조정이 이루어져야 합니다. 출력층 가중치 행렬에서 정답에 해당하는 단어를 표현하는 칼럼의 벡터는 최종적으로 높은 점수를 산출할 수 있도록 조정될 것이고, 나머지 칼럼들은 상대적으로 낮은 점수를 산출하도록 조정될 것입니다. 그래야 최종 손실이 낮아질테니까요. 

그런데 위에서 우리가 고안한 것처럼 그냥 '정답'에 해당하는 단어의 점수만 산출해서 시그모이드를 통해 확률꼴로 전환하고 손실을 계산한 후 그것에 기반해서 학습하면, 모델의 변화 가능성이 매우 제한됩니다. 우선 출력층 가중치 행렬에서 정답에 해당하는 단어의 칼럼 파트만 조정될 것입니다. 왜냐하면, 나머지 파트는 최종 손실 산출에 전혀 개입하지 않았기 때문입니다. 10장에서 말씀드렸듯 신경망 모델의 기본 학습 알고리즘은 각 파라미터가 손실에 대해 가지는 미분 계수를 활용하는 것이었습니다. 각 파라미터가 미세하게 움직일 때 손실이 어떻게 반응하는지 보고, 손실이 줄어드는 방향으로 파라미터를 조정한다는거죠. 그런데 각 파라미터가 손실에 대해 0이 아닌 미분 계수를 가지려면, 그 파라미터가 손실 계산에 개입해야 합니다. 그래야 그 파라미터가 변동함에 따라 손실이 변동할 가능성이 생기죠. 그런데, 만약 '정답'에 해당하는 단어의 점수만 산출해서 활용한다면, W'라는 출력층 가중치 행렬에서 딱 하나의 칼럼만 활용해서 최종 점수가 계산됩니다. 나머지 칼럼들은 전혀 개입이 없죠. 이건, 나머지 파트는 손실과도 무관하다는 뜻입니다. 그러면 당연히 나머지 파트가 손실에 대해 가지는 미분 계수는 0이 됩니다. W'이라는 출력층 가중치 행렬에서 정답 파트 이외의 칼럼의 성분은 손실과 무관하게 되어 학습에서 배제된다는 말입니다.  

이렇게 W'에서 일부 칼럼만 학습에서 변동하면, 그 영향은 W, 즉 은닉층 가중치 행렬까지 전파됩니다. 우리는 W에 담길 단어의 벡터 표현이, 유사한 의미를 지닌 단어들은 유사한 벡터로, 상이한 의미를 지닌 단어들은 상이한 벡터로 표현되기를 원합니다. 이를 위해서는 비슷한 단어들이 서로 유사하게 표현되도록 끌어당기는 힘 만큼이나, 서로 다른 의미의 단어들이 서로 멀어지려는 힘이 학습에 필요합니다. 그런데 W'에서 정답에 해당하는 단어를 표현하는 칼럼만 조정되면, 후자의 힘이 사라집니다. 

W의 관점에서 학습 과정을 생각해봅시다. Word2Vec에서 각 케이스마다 모델이 조정될 때, W, 즉 은닉층 가중치 행렬 파트에서는 입력된 단어들에 해당하는 단어의 벡터 표현이 조정 압력을 받습니다. Skip-gram 상황을 예로 들자면, '정권'이라는 단어가 입력되었고 '부정선거'라는 맥락 단어를 예측해야 한다고 하죠. 그러면 '정권'이라는 단어가 W에서 가지는 벡터 표현이 '부정선거'라는 단어가 W'에서 가지는 벡터 표현과 dot product 되었을 때 높은 점수를 가져야 합니다. 그래야 손실이 줄어들죠. 그러므로 W의 '정권'에 해당하는 단어를 표현하는 벡터도, W'의 '부정선거' 단어 파트의 벡터 표현과 dot product가 일어났을 때 높은 점수를 산출할 수 있는 방향으로 조정이 일어날 것입니다. 하지만 W'에서 다른 단어에 해당하는 파트와 dot product가 일어났을 때 낮은 점수를 가지는 방향으로 조정이 이루어지지는 않습니다. 왜냐하면, 앞서 말했듯이 다른 단어들, 그러니까 오답에 해당하는 단어들은 아예 손실 계산에서 고려를 하지 않았거든요. 그들이 손실에 개입하지 않으니, 그들과 곱해져서 무슨 점수를 내든 상관이 없어진 셈입니다. 

요컨대, 각 문제의 '정답'에 해당하는 단어의 점수와 확률만 계산해서 학습시키려는 변형은, 계산량을 줄인다는 점에서는 괜찮은 아이디어지만, 학습이라는 관점에서는 중요한 점을 놓치게 됩니다. 즉, **모델이 오답을 산출하지 않도록 조정되는 힘이 사라진다는 말입니다.** 이건, W와 W'에 담길 단어 벡터 표현의 관점에서 보면, '유사한 단어들이 유사한 방향으로 변화하는' 힘은 받게 되나, '상이한 단어들이 다른 방향으로 변화하는' 힘은 받지 않는 문제를 만듭니다. 

여담입니다만, 그래서 기본 모형에서 소프트맥스를 거쳐 만들어진 정답 단어의 확률은, '모든 대안을 고려한 상태에서 신경망 모델이 정답에 해당하는 단어를 실제로 정답이라고 판정하는 확률'이었던 반면, 이걸 단순화해서 정답 단어 점수만 산출하고 그걸 시그모이드를 거쳐서 만든 확률은, '다른 대안을 고려하지 않는 독립 상태에서 모델이 정답에 해당하는 단어가 그럴 듯한 단어라고 판정하는 확률'이었던 셈입니다. 만약 확률이라는 말을, 발생할 수 있는 가능한 사건들에 대한 상대적인 가중치라고 이해한다면, 후자는 사실 확률이라고 부르기도 애매합니다. 그냥 확률의 형식을 한 독립적인 점수에 가깝죠. 그러니 전자에서는 모델이 전반적으로 수정 압력을 받는 반면, 후자에서는 일부만 수정 압력을 받습니다. 그리고 그건, 말씀드렸듯이 최종 산물인 단어의 벡터 표현에 문제를 만듭니다.

#### 6.4.3. Negative sampling: 일부 오답의 도입

요컨대 우리는 연산 비용은 많이 들지만 학습은 잘 되는 옵션과 (기본 모형) 연산 비용은 낮지만 학습이 잘 안되는 옵션 (정답에 해당하는 단어만 고려하는 단순화 모형) 사이에 있는 셈입니다. 절충안은 없을까요? 있습니다. 그게 negative sampling 입니다. negative sampling은 모든 단어를 고려하지 않는 대신, 정답에 해당하는 단어와, '일부' 오답에 해당하는 단어를 손실 계산에 고려합니다. 그게 바로 오답 사례, negative sample이죠. 이걸 개입시킨다고, negative sampling이라고 부르는 것입니다. 

예를 들어 전체 어휘수가 10000개라고 하죠. 그러면 정석으로 접근하면, 이 10000개의 어휘마다 다 정답에 해당할 확률을 산출해야 합니다. 그런데 이게 너무 힘들죠. 그래서 대신 이렇게 합니다. 해당 문제의 정답에 해당하는 단어가 모델에서 산출하는 점수를 산출합니다. 여기에 더해, 분석자가 설정하는 적당한 숫자의 오답에 해당하는 단어가 모델에서 산출하는 점수를 계산합니다. 적당한 숫자는 설정하기 나름이지만, 여기서는 5로 했다고하죠. 즉 오답에 해당하는 다섯 개 단어를 설정하고, 모델이 그 다섯 개 오답 단어에 대한 점수도 산출하도록 한다는 말입니다. 그리고 그렇게 산출된 여섯 개의 점수를 (정답 단어 점수 1개, 오답 단어 점수 5개) 각각 시그모이드에 넣습니다. 정답은 그대로 넣고, 오답은 마이너스를 붙여서 넣습니다. 오답의 경우 점수가 크면 클수록 모델이 잘못 작동하고 있다는 뜻이니, 최초 점수가 크면 클수록 시그모이드에 넣을 점수가 작아지도록 설계하는 셈입니다. 이를 통해 정답에 해당하는 단어는 시그모이드를 거쳐 나온 숫자가 1에 가까워야 손실이 작도록하고, 오답에 해당하는 5개 단어는 0에 가까워야 손실이 작아지도록 설계합니다. 공식으로 보면 아래처럼 한다는 말입니다. Skip-gram 상황을 가정하겠습니다. 

$$
\begin{aligned}
L = -\log{\sigma(\mathbf{u}_{o}^{\top}\mathbf{v}_{c})} - \sum_{i=1}^{K}\log {\sigma(-\mathbf{u}_{i}^{\top}\mathbf{v}_{c})}
\end{aligned}
$$

여기서 $\mathbf{u}_{o}$는 정답에 해당하는 단어가 출력층 가중치 행렬에서 가지는 벡터 표현이고, $\mathbf{v}_{c}$는 입력된 중심 단어가 은닉층 가중치 행렬에서 가지는 벡터 표현이며, $\mathbf{u}_{i}$는 i번째 오답, 즉 negative sample이 출력층 가중치 행렬에서 가지는 벡터 표현입니다. K는 내가 선정한 오답의 개수이죠. 그리고 $\sigma$ 는 시그모이드 함수를 요약한 것입니다. 

정답의 점수는 그대로, 그리고 오답의 점수는 마이너스를 붙여서 각각 시그모이드 함수를 통과시켜서 로그를 붙이고 다시 마이너스를 붙인 꼴입니다. 이렇게 하면 정답의 점수는 높으면 높을수록 손실이 작아지고, 오답의 점수는 낮으면 낮을 수록 손실이 작아지죠. 위와 같은 형태의 손실 계산을 Binary Cross-entropy라고 부릅니다.

이렇게 손실값을 산출해서 학습시키면 모델은 정답에 해당하는 단어 점수는 높이는 방향으로 파라미터를 조정할 것이고, 오답에 해당하는 단어 점수는 낮추려고 파라미터를 조정할 것입니다. 우리가 우려한 사항을 어느 정도는 해결해주는 거죠. 더불어 전체 단어가 아니라 소수의 오답만 연산에 개입시키니, 연산의 효율도 어느 정도는 달성하는 것입니다. 즉 일종의 절충안입니다.

다만 이 경우, 소수의 오답을 어떻게 선정할 것이냐는 문제가 남습니다. 즉 정답이 아닌 다른 단어 K개를 어떻게 선택할 것이냐는 문제가 남는다는 말입니다. 우선 '자주 등장하는 단어'를 우선 고려하는 방식이 존재할 수 있습니다. 아무래도 자주 등장하는 단어는 다양한 맥락에서 등장하고, 그래서 모델이 여러 맥락에서 이들과 정답을 잘 구분해주는 것이 전체적인 성능에 중요합니다. 이를 위해 데이터에 출현한 빈도에 기반하여 단어의 확률 분포로 만들고, 그 확률 분포에 기반하여 무작위로 추출하게 되면, 빈도가 높았던 단어가 더 높은 확률로 오답으로 선택될 것입니다. 

다만 이럴 경우 확률이 작은 단어는 필요 이상으로 무시될 가능성이 있습니다. 단어별 출현 빈도가 매우 치우쳐져 있을 공산이 크기에 (보통 그렇습니다. 자주 사용되는 단어는 엄청 많이 활용되고 그렇지 않은 단어는 아주 적게 활용되지요.), 약간 확률 분포를 평탄화해주는 작업을 하기도 합니다. Word2Vec의 제안자는 이를 아래와 같은 수식으로 달성했습니다. 

$$
\begin{aligned}
P(w_i)' = \frac{P(w_i)^{0.75}}{\sum_i^n P(w_i)^{0.75}}
\end{aligned}
$$

이렇게 하면 단어간 확률의 순위가 뒤집히지는 않지만, 확률의 차이가 줄어드는 효과가 생깁니다. 즉 확률 분포가 약간 평탄화되는거죠. 이렇게 조정된 확률 분포에 근거하여 오답을 고르면, 저빈도 단어가 좀 더 포함되는 효과가 생깁니다.

#### 6.4.4. 실제 구현

구현 파트는 역시 변동되는 부분이 아주 많지는 않습니다. 데이터를 전처리하는 파트는 모두 그대로죠. 다만 skip-gram의 핵심이 '모든 단어에 대해 점수를 계산해서 확률 분포를 얻고 그것에 근거하여 손실을 계산하는 대신, 정답과 일부 오답에만 근거해서 점수를 산출하고 그것에 기반해서 손실을 계산한다' 는 것이니, 1) 모델 구조를 적합하게 변경하고, 2) 오답을 선정하는 함수를 마련하고, 3) 훈련 루프에서 손실을 계산하는 방식을 변경하는 일이 필요합니다. 그러니, 일단 변치 않는 부분을 실행하고, 차례차례 해봅시다. 

일단 우리가 skipgram 디자인을 적용하기 위해 만들어둔 데이터와 사전은 그대로 활용하면 됩니다. Skipgram_DATA, W2V_VOCAB이 그것입니다. 데이터 셋 설정 방식도 바뀔게 없죠. 다만 그냥 다시 한 번 초기화만 해주겠습니다.

In [24]:
dataset = SkipgramDataset(Skipgram_DATA)
dataloader = DataLoader(dataset, batch_size=128, shuffle=True)

# shape 확인
x_example, y_example = next(iter(dataloader))
print("x_example shape:", x_example.shape)  # [batch_size]
print("y_example shape:", y_example.shape)  # [batch_size]

x_example shape: torch.Size([128])
y_example shape: torch.Size([128])

이제 변화하는 첫번째 부분입니다. 모델이 변화해야 합니다. 아래와 같이 변화시킵니다.

In [25]:
class SkipgramNegSampling(nn.Module):
    def __init__(self, vocab_size, embed_size):
        super().__init__()
        self.input_embedding = nn.Embedding(vocab_size, embed_size)
        self.output_embedding = nn.Embedding(vocab_size, embed_size)

    def forward(self, center_words, pos_words, neg_words):
        # center_words: [batch]
        # pos_words: [batch]
        # neg_words: [batch, num_neg]

        center_emb = self.input_embedding(center_words)      # [batch, embed]
        pos_emb = self.output_embedding(pos_words)           # [batch, embed]
        neg_emb = self.output_embedding(neg_words)           # [batch, num_neg, embed]

        # positive score
        pos_score = torch.sum(center_emb * pos_emb, dim=1)   # [batch]

        # negative score
        neg_score = torch.bmm(neg_emb, center_emb.unsqueeze(2)).squeeze(2)  
        # [batch, num_neg]

        return pos_score, neg_score

먼저 눈에 띄는 것이 출력층 변환도 linear layer 대신 nn.Embedding을 활용하는 것입니다. 말씀드렸듯, 모든 단어에 대한 점수를 계산하지 않는다면, 굳이 완전연결층을 쓸 필요가 없습니다. 그냥, 정답에 해당하는 출력층 가중치 행렬 칼럼과 일부 오답에 해당하는 출력층 가중치 행렬 칼럼을 가져와서 각각 점수를 산출하면 되죠. 이 부분을 nn.Embedding으로 구현할 수 있습니다. 즉 이제 두 개의 look-up table이 은닉층 가중치 행렬과 출력층 가중치 행렬 역할을 하는 셈입니다. 

그런 다음, 이 모델이 산출하는 점수를 두 개로 나눠서 반환해줘야 합니다. 하나는 정답에서 나오는 점수이고 다른 하나는 오답에서 나오는 점수이죠. 앞서 설명드린 손실 계산을 위해 기초 점수를 만드는 것입니다. 

자 그런데 이게 돌아가려면 오답을 선택하는 메커니즘이 필요하죠. 아래와 같이 함수를 설정해보겠습니다.

In [26]:
def build_negative_sampling_distribution(vocab, smoothing=0.75, device="cpu"):
    counts = []

    for idx in range(vocab.num_words()):
        word = vocab.index2word(idx)
        count = vocab.get_word_count(word)

        if word == UNK_symbol:
            count = 0

        counts.append(count)

    counts = torch.tensor(counts, dtype=torch.float32, device=device)
    probs = counts.pow(smoothing)
    probs = probs / probs.sum()
    return probs


def sample_negative_excluding_targets_fast(targets, num_neg, neg_distribution):
    """
    targets: shape = (batch_size,)
    num_neg: 각 샘플당 negative sample 개수
    neg_distribution: shape = (vocab_size,)

    return:
        neg_samples: shape = (batch_size, num_neg)
    """
    device = neg_distribution.device
    batch_size = targets.size(0)

    # 1차로 한 번에 샘플링
    neg_samples = torch.multinomial(
        neg_distribution,
        num_samples=batch_size * num_neg,
        replacement=True
    ).view(batch_size, num_neg).to(device)

    # 정답과 겹치는 위치를 찾아서 재샘플링
    mask = (neg_samples == targets.unsqueeze(1))

    while mask.any():
        num_to_resample = mask.sum().item()

        new_samples = torch.multinomial(
            neg_distribution,
            num_samples=num_to_resample,
            replacement=True
        ).to(device)

        neg_samples[mask] = new_samples

        mask = (neg_samples == targets.unsqueeze(1))

    return neg_samples

build_negative_sampling_distribution 함수는 앞서 설명드린 확률 분포 평탄화 함수입니다. 천천히 보시면 그냥 단순히 그 논리를 반영한 것입니다. 단어 인덱스별로 빈도를 가져오고, 그걸 확률 분포로 만들고, 평탄화 작업을 하는거죠. 그런데 unk라는 특수 토큰은 뽑히지 않도록 한 것입니다. sample_negative_excluding_targets는, 그렇게 조정된 확률 분포를 가져와서 샘플링하되, 정답 단어에 해당하는 단어를 포함하지 않을 때까지 반복하는 방식입니다. 우연히 정답이 뽑혀와서 네거티브 샘플에 들어갈 수도 있으니까요. 

자 이 상태에서 훈련 루프를 담당하는 함수를 아래와 같이 만들어 볼 수 있습니다.

In [27]:
embed_size = 50

Skipgram_model_NegSampling = SkipgramNegSampling(W2V_VOCAB.num_words(), embed_size).to(DEVICE) # 모델 설정
optimizer = torch.optim.Adam(Skipgram_model_NegSampling.parameters(), lr=0.002) #최적화 알고리즘 설정

neg_distribution = build_negative_sampling_distribution(
    vocab=W2V_VOCAB,
    smoothing=0.75,
    device=DEVICE
)

In [28]:
def train_Skipgram_NegSampling_manual(model, dataloader, num_epochs, optimizer, neg_distribution, num_neg=5):
    all_epoch_losses = []

    total_batches = len(dataloader)
    print_interval = max(1, total_batches // 5)
    total_data_len = len(dataloader.dataset)

    for epoch in range(1, num_epochs + 1):
        model.train()
        epoch_losses = []

        for batch_idx, (x, y) in enumerate(dataloader, 1):
            x, y = x.to(DEVICE), y.to(DEVICE)

            neg_y = sample_negative_excluding_targets_fast(
                targets=y,
                num_neg=num_neg,
                neg_distribution=neg_distribution
            )

            pos_score, neg_score = model(x, y, neg_y)

            pos_loss = -torch.log(torch.sigmoid(pos_score) + 1e-10)               # [batch]
            neg_loss = -torch.log(torch.sigmoid(-neg_score) + 1e-10).sum(dim=1)  # [batch]
            
            loss = (pos_loss + neg_loss).mean()

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            loss_value = loss.item()
            epoch_losses.append(loss_value)

            if batch_idx % print_interval == 0 or batch_idx == total_batches:
                current_data = batch_idx * dataloader.batch_size
                print(f"{min(current_data, total_data_len)}/{total_data_len} — loss: {loss_value:.4f}")

        avg_loss = sum(epoch_losses) / len(epoch_losses)
        all_epoch_losses.append(avg_loss)
        print(f"[Epoch {epoch}] Average Loss: {avg_loss:.4f}")

    return all_epoch_losses

자 전에 비해 큰 변동은 없습니다. 다만 앞에서 설명드린 손실계산 방식에서 변동을 가져오기 위해, 해당 파트만 조정이 되어 있지요. 정답에서 나온 손실과 오답에서 나온 손실을 결합하여 손실을 정의하고, 그것에 기반하여 모델을 업데이트합니다. 그 이외에는 동일합니다. 그리고 실행시키는거죠.

In [29]:
losses_manual = train_Skipgram_NegSampling_manual(
    Skipgram_model_NegSampling,
    dataloader,
    num_epochs=10,
    optimizer=optimizer,
    neg_distribution=neg_distribution,
    num_neg=5
)

26496/132496 — loss: 12.6551
52992/132496 — loss: 11.2578
79488/132496 — loss: 10.5827
105984/132496 — loss: 10.0230
132480/132496 — loss: 8.9051
132496/132496 — loss: 9.7771
[Epoch 1] Average Loss: 11.9963
26496/132496 — loss: 8.0935
52992/132496 — loss: 7.6561
79488/132496 — loss: 6.3670
105984/132496 — loss: 6.5511
132480/132496 — loss: 5.6009
132496/132496 — loss: 6.3778
[Epoch 2] Average Loss: 7.1807
26496/132496 — loss: 5.3947
52992/132496 — loss: 5.0844
79488/132496 — loss: 3.7660
105984/132496 — loss: 4.7233
132480/132496 — loss: 4.6789
132496/132496 — loss: 4.8886
[Epoch 3] Average Loss: 4.7796
26496/132496 — loss: 3.6306
52992/132496 — loss: 3.4467
79488/132496 — loss: 3.3816
105984/132496 — loss: 3.5432
132480/132496 — loss: 3.7974
132496/132496 — loss: 3.9790
[Epoch 4] Average Loss: 3.5871
26496/132496 — loss: 3.0301
52992/132496 — loss: 3.0270
79488/132496 — loss: 2.7638
105984/132496 — loss: 3.1412
132480/132496 — loss: 3.0760
132496/132496 — loss: 2.1265
[Epoch 5] Average Loss: 3.0157
26496/132496 — loss: 2.7721
52992/132496 — loss: 2.6430
79488/132496 — loss: 2.7037
105984/132496 — loss: 2.8390
132480/132496 — loss: 2.6876
132496/132496 — loss: 2.6776
[Epoch 6] Average Loss: 2.6932
26496/132496 — loss: 2.6442
52992/132496 — loss: 2.4240
79488/132496 — loss: 2.4020
105984/132496 — loss: 2.4808
132480/132496 — loss: 2.3560
132496/132496 — loss: 2.4730
[Epoch 7] Average Loss: 2.4994
26496/132496 — loss: 2.7024
52992/132496 — loss: 2.1770
79488/132496 — loss: 2.5074
105984/132496 — loss: 2.4510
132480/132496 — loss: 2.3409
132496/132496 — loss: 2.5340
[Epoch 8] Average Loss: 2.3694
26496/132496 — loss: 2.1299
52992/132496 — loss: 2.2440
79488/132496 — loss: 2.2938
105984/132496 — loss: 2.1705
132480/132496 — loss: 2.2988
132496/132496 — loss: 1.9079
[Epoch 9] Average Loss: 2.2723
26496/132496 — loss: 2.2593
52992/132496 — loss: 2.2313
79488/132496 — loss: 2.0996
105984/132496 — loss: 2.0814
132480/132496 — loss: 2.3208
132496/132496 — loss: 2.4483
[Epoch 10] Average Loss: 2.2000

돌아가는 속도를 보면, 충분히 빠르게 느껴지지 않으실 수 있습니다. 이건 여러 원인에서 기인합니다. 일단, 이론적으로 소프트맥스가 비싼 연산은 맞습니다. 그런데 그게 파이토치에서는 매우 잘 최적화되어 있습니다. 그런데 네거티브 샘플링을 우리가 기초적으로 구현하는 과정에서는 소프트맥스는 사라졌지만 이외의 여러 계산이 들어옵니다. 일단 오답을 추출하는 과정이 있죠. 이것이 사실 다 시간을 잡아먹는 과정입니다. 

아마 개발자 분들이 이쪽도 여러 단계로 최적화를 한다면 원리적으로 네거티브 샘플링을 동원한 쪽이 더 빠를 것이라 봅니다. 다만 지금은 그냥 어떻게 구현되는지 이해하기 위해 쓴 코드에 가까워서 속도 개선이 느껴지지 않는 것입니다. 다만 우리의 목표는 아이디어를 이해하는 것이니, 이 정도로 넘어가도록 합시다^^

나머지는 동일합니다. 아래와 같이 원래 하던 걸 해봅시다.

In [30]:
embedding_matrix_4 = Skipgram_model_NegSampling.input_embedding.weight.detach().cpu()
print(embedding_matrix_4.shape)   # [vocab_size, embed_size]

def get_word_vector(word, vocab, embedding_matrix):
    idx = vocab.word2index(word)
    return embedding_matrix[idx]

word = "감동"
vec = get_word_vector(word, W2V_VOCAB, embedding_matrix_4)
print(word, vec[:10], vec.shape)  # 앞 10개만 보기

import torch.nn.functional as F

def most_similar(word, vocab, embedding_matrix, topn=10):
    if word not in vocab._word2index:
        return f"'{word}' not in vocab."

    idx = vocab.word2index(word)
    query_vec = embedding_matrix[idx].unsqueeze(0)  # [1, embed_size]

    sims = F.cosine_similarity(query_vec, embedding_matrix, dim=1)
    sims[idx] = -1.0  # 자기 자신 제외

    top_indices = torch.topk(sims, topn).indices.tolist()
    return [(vocab.index2word(i), float(sims[i])) for i in top_indices]

most_similar("감동", W2V_VOCAB, embedding_matrix_4, topn=10)

torch.Size([1505, 50])
감동 tensor([ 0.2021, -0.1956,  0.1283, -0.0842, -0.3074, -0.0984,  0.2660,  0.0477,
        -0.5784,  0.0674]) torch.Size([50])

[('없', 0.6510704159736633),
 ('영화', 0.6440816521644592),
 ('마음', 0.6070104837417603),
 ('슬프', 0.5961675643920898),
 ('밴드', 0.5923951268196106),
 ('재미있', 0.5912392735481262),
 ('이야기', 0.569161593914032),
 ('꽤', 0.5645685195922852),
 ('죽음', 0.5630531907081604),
 ('잔혹', 0.5613428354263306)]

## 7. 연구적 활용 방식과 한계

자 지금까지 우리는 매우 긴 과정을 통해 Word2Vec의 구조와 작동을 이해하고, 파이토치를 통해 구현해봤습니다. 파이토치를 통해 구현 실습을 해 본 것도, 사실 모델의 구조와 기능에 대한 이해를 심화시키기 위함이었습니다. 실제 프로젝트에서 Word2Vec을 표준적인 세팅에서 이용하신다면, Gensim 같은 라이브러리가 이미 최적화가 잘 되어 있으니, 오히려 좋은 옵션일 수도 있습니다. 하지만 Gensim과 메뉴얼만 보고 실습을 하면 실제 모델의 구조와 최적화 포인트, 나아가 모델의 장/단점을 명료하게 파악하기가 어렵기에, 일부러 좀 돌아온 셈입니다. 더불어 파이토치에 기반한 신경망 모델 작성 및 학습에 익숙해지시도록 하는 목적도 있었고요. 돌아오느라 괴로움도 있었겠지만 즐거움도 있었던 과정이기를 바랍니다^^

자, 그런데 이거 어디에다가 쓰는걸까요? 서두에서 말씀드렸던 것처럼, 가장 기본적으로는 Word2Vec을 포함한 embedding 결과는 언어를 입력 혹은/그리고 출력으로 삼는 여러 모델에서 활용됩니다. 요즘 여러 언어 인공지능이 존재하죠. 번역도 해주고, 요약도 해주고, 분류도 해줍니다. 그런데 이게 다 넓게 보자면 통계 모델인데, 그래서 뭐가 되었든 입력과 출력은 수치 정보 형태입니다. embedding은 언어와 이 수치정보 사이의 가교 역할을 하는거죠. 좋은 embedding은 동일한 모델의 성능도 향상시키는 효과를 가지고, 그래서 Word2Vec과 같은 임베딩 기법에 사람들이 관심을 가지는 것입니다. 

그런데 이런 용도의 활용은, 그러니까 현업에서 각종 언어 관련 모델에 들어갈 데이터 생산용으로서의 Word2Vec 활용은 과거에 비해 줄었다고 보는게 적절할 듯합니다. Word2Vec이 나온지도 이미 10년이 훌쩍 넘었고, 다른 종류의 embedding 방법도 많거든요. 사실 Word2Vec은 나름의 한계를 가집니다.

기본적으로 Word2Vec은 정적인 스타일입니다. 정적 임베딩 (static embedding) 기법이라고 부르기도 합니다. 이건, 하나의 단어/토큰을 하나의 벡터로 옮긴다는 뜻입니다. 이게 무슨 문제일까 싶지만, 같은 단어가 맥락에 따라 의미와 가치가 크게 달라지는 문제에 대응하기 어렵습니다. 예를 들어 2장에서 들었던 예처럼 '작고 귀여운 개가 지나간다'와 '저 개만도 못한 인간'이라는 문장은 둘 다 '개'라는 단어를 포함하고 있지만, '개'가 만드는 의미나 뉘앙스는 각 문장에서 매우 다릅니다. 나아가 명시적인 다의어도 있습니다. '이번 가을엔 배가 참 맛있네' 할 때 '배'와 '바다에 배가 많다'라고 할 때 '배'는 아예 다른 대상을 가리킵니다. 그런데 이런 상황에서 '개'와 '배'를 하나의 벡터로 옮기면, 여러 경우에서 목적에 부합하지 않습니다. 뒤에서 배울 BERT 등의 기법이 이를 해결하기 위한 맥락적 임베딩 (contextual embedding) 기법입니다.

그러면 Word2Vec은 이제 딱히 쓸 일이 없는 과거의 기법일 뿐일까요? 저는 그렇지 않다고 생각합니다. Word2Vec이 최근 많이 활용되는 맥락적 임베딩 기법에 비해 섬세함이 떨어지는 것은 사실입니다. 하지만 그것이 일반적으로 Word2Vec이 좋지 않은 모델이라는 뜻은 결코 될 수 없습니다. 왜냐하면, 모든 상황에서 섬세함이 모델이 가져야 할 가장 좋은 가치가 아니기 때문입니다. **상황과 목적에 따라, 모델에게 요구되는 가치가 달라질 수 있습니다. 어떤 때에는 섬세함이 어떤 때에는 학습 속도가, 또 어떤 때에는 대략적인 패턴 파악이 중요할 때가 있습니다.**

최근 BERT를 비롯한 맥락적 임베딩이 많이 언급되는 것은, 언어 자료의 섬세한 의미 및 뉘앙스 구분이 필요한 상황이 자주 등장하기 때문이었습니다. 예를 들어 챗봇이 응답을 잘 하려면, 지금 유저가 무슨 뉘앙스와 정서로 어떤 말을 입력하는지 알아야 합니다. 그런걸 하기 위해서는 맥락적 임베딩 기법이 확실히 유리하죠. 유저들의 개별적 요구를 잘 만족시키기 위한 언어 기반 서비스에서는 이런 모델이 필요합니다. 

하지만 매 입력의 섬세한 차이보다, 전체 데이터에서 나타나는 대략적인 패턴을 빠르고 경제적으로 파악해야 하는 상황도 있습니다. 연구 상황이 보통 그렇죠. 현황을 파악하고 우리가 직관적으로 파악하지 못하는 사회의 특징을 포착하기 위한 여러 연구에서는 개별 케이스를 깊이 있게 이해하는 것을 목적으로 하지 않는 경우가 많습니다. (물론 질적 연구 등 목표가 반대인 경우도 있지만, 여기서는 통상적인 양적 연구를 가정할게요) 오히려 그 케이스들이 모인 데이터에서 나타나는 가장 주되고 일반적인 패턴을 찾아내는 것이 목표인 경우가 많죠. 

언어 자료도 마찬가지입니다. 개별 기사에서 어떤 토큰/단어의 뉘앙스나 의미를 정확히 파악하는 것이 필요할 수도 있지만, 20만개의 기사가 모인 자료에서 어떤 대상을 가리키는 토큰/단어의 주된 의미나 용법을 파악하는게 필요한 경우도 있다는 것입니다. 언어 자료로 연구를 하는 사람들, 예를 들어 이 강의의 제목처럼 마음의 구조를 대량 언어 자료에서 탐구하려는 사람들은 이런 상황에 자주 처하죠. 

그리고 그런 상황에 Word2Vec은 괜찮은 옵션이 될 수 있습니다. 상대적으로 단순한 모델이라 학습 속도가 빠르고, 모든 토큰을 하나의 벡터로 전환하기에 '가장 주된 의미'를 포착하는데 적절합니다. 즉 앞서 언급한 단점이 목적이 변화함에 따라 (데이터의 대략적인 패턴 캐치) 장점이 되는거죠.

실제로 이런 장점을 이용하여 창의적인 방식으로 활용한 연구가 다수 존재합니다. 저는 Kozlowski, Taddy, Evans가 수행한 이 연구 (Kozlowski, Austin C., Matt Taddy, and James A. Evans. 2019. “The Geometry of Culture: Analyzing the Meanings of Class through Word Embeddings.” American Sociological Review 84(5):905-949.)가 그런 면에서 아주 인상적이었습니다. 직접 찾아보셔서 읽어보시면 정확히 아실테지만, 이 연구는 대량 언어 자료를 기반으로 Word2Vec을 학습시키고, 그 결과 나온 각 단어의 벡터 표현을 통해 문화를 연구할 수 있다고 제안합니다. 

예를 들어 스포츠 종목마다 문화적 이미지가 존재할 수 있습니다. 골프 같은 것은 부자 스포츠 같은 느낌이 나고, 복싱은 반대로 헝그리 정신을 보여주는 것 같습니다. 그런데 만약 단어들이 벡터로 전환되어 있다면, 즉 숫자로 전환되어 있다면, 이걸 계산을 통해 보여줄 수 있습니다. 예를 들어 '골프'라는 단어를 표현하는 벡터와 '부자' 혹은 '풍요로움'이라는 단어를 표현하는 벡터 사이의 유사성을 계량하는 거죠. 이처럼 벡터와 벡터의 유사성을 보는 것은 어렵지 않고 방식도 다양합니다. 코사인 유사도 (cosine similarity)를 포함하여 여러 지표가 존재하지요. 저 연구는 이런 기본적인 방법을 활용하여 다양한 문화적 차원을 탐색합니다. 

보건의료계통 학생분들이 관심 있을 법한 연구도 있습니다. Best와 Arseniev-Koehler가 수행한 이 연구인데요 (Best, R. K., & Arseniev-Koehler, A. (2023). The Stigma of Diseases: Unequal Burden, Uneven Decline. American Sociological Review, 88(5), 938-969.), 위 연구와 유사한 방식으로 언어 자료에서 '질병에 대한 낙인 정도'를 연구한 부분을 포함하고 있습니다. 질병이 단순히 생물학적인 고통만을 야기하는 것이 아니라, 사회문화적 의미를 통해 영향력을 (주로 고통을) 만들어냄은 잘 알려져 있습니다. 그런데 그 정도를 계량하는 것은 쉽지 않은 일입니다. 그런데 이 연구는 대량 언어 자료에서 각 질병 명칭의 벡터가 혐오나 부정적 편견을 가리키는 단어의 벡터와 얼마나 유사한지를 보는 방식으로 이에 대한 분석을 시도합니다. 타당성 여부와 별개로, 흥미로운 아이디어라고 생각합니다. 

Word2Vec은 흥미로운 모델입니다. 언어라는 질적인 대상을 수치적인 표현으로 전환하려는 시도를 매우 유용한 형식과 적당한 완성도로 해내고 있습니다. 너무 모델이 복잡하면 대체 그 안에서 어떤 일이 일어나는지 알 수 없는데, 직관적으로도 이해 가능한 수준의 모델 복잡도와 최적화 전략을 갖고 있지요. 그래서인지 연구적으로 활용하는 경우도 많습니다. 특히 최근 전산사회과학 (computational social science)에서는 없어서는 안될 기법 중 하나입니다. 물론 지금까지의 방식 말고도 다양한 방식이 활용이 존재할 수 있습니다. 이번 강의와 여러 연구 사례가, 이걸 보시는 분들의 영감을 자극할 수 있기를 바랍니다. 이걸로 11장은 마치겠습니다.